// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/screens/home_screen_options.proto" (package "screens", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message screens.DummyHomeScreen
 */
export interface DummyHomeScreen {
}
// @generated message type with reflection information, may provide speed optimized methods
class DummyHomeScreen$Type extends MessageType<DummyHomeScreen> {
    constructor() {
        super("screens.DummyHomeScreen", []);
    }
    create(value?: PartialMessage<DummyHomeScreen>): DummyHomeScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DummyHomeScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DummyHomeScreen): DummyHomeScreen {
        return target ?? this.create();
    }
    internalBinaryWrite(message: DummyHomeScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message screens.DummyHomeScreen
 */
export const DummyHomeScreen = new DummyHomeScreen$Type();
