// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/screens/payment_screen_options.proto" (package "screens", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message screens.DummyPaymentScreen
 */
export interface DummyPaymentScreen {
}
// @generated message type with reflection information, may provide speed optimized methods
class DummyPaymentScreen$Type extends MessageType<DummyPaymentScreen> {
    constructor() {
        super("screens.DummyPaymentScreen", []);
    }
    create(value?: PartialMessage<DummyPaymentScreen>): DummyPaymentScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DummyPaymentScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DummyPaymentScreen): DummyPaymentScreen {
        return target ?? this.create();
    }
    internalBinaryWrite(message: DummyPaymentScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message screens.DummyPaymentScreen
 */
export const DummyPaymentScreen = new DummyPaymentScreen$Type();
