export const TextComponentConstant={
    Aadhartitle: "Use Aadhar details to open an \n account",
    Aadhaarsubhead: "Our partner Bank will verify your \n KYC with Aadhaar and open an account with \n a maximum deposit limit of Rs. 50,000 in a \nfinancial year. KUBAIR does not store or use your \n Aadhaar details\nYou can always upgrade to a full-fledged\naccount later",
    Aadhaarsubhead1:"By proceeding, you consent to the above and agree\nthat no other account has been or will opened \nusing OTP-based KYC with another Regulated Entity",
    Splashtext:"I Understand",
    Aadhaardetailtitle: "Enter your Aadhaar details",
    SecureComponentText:"Your Aadhaar details are protected",
    checkboxText:"I voluntarily provide my Aadhaar number and \nprovide my consent to Bank to obtain my\n aadhaar details from UIDAI for establishing\nmy identity. ",
    AadhaarotpTitle: "Verify with OTP",
    Aadhaarotpsubtitles: "An OTP was sent to your Aadhaar-registered \n mobile number. For security reasons, we won't \n auto-read your Aadhaar OTP, Please type it \n out below",
    Resend: "Resend",
    EditText: "Want to edit Aadhaar Number Click on ",
    Next: "Next",
    FallbackTexttitle:"Are you sure you want to exit\nAadhar verification?",
    Fallbacksubhead: "If you exit, you will have to start your \n Aadhaar verification process again",
    Yes: "Yes",
    Close: "Close",
}
export const ColorConstant={
    bgcolor: "#FFFFE4",
    subhead: "#262123",
    subhead1: "#7E7E7E",
    splashcolor: '#F7F2E8',
    primary:'#000000',
    buttoncolor:'#D05F33',
    seconarycolor:"gray",
    boxcolor:'#262123',
    textcolor:'black',
    aadharidetailsplaceholder:'#7E7E7E',
    inputtext:"#421C25",
    secureComponentcolor: "#E0E0E0",
    radiotextColor:"#262123",
    bordercolors:'#B2B2B2',
    secondary: '#2FA298',
        COLOR_BACKGROUND: "#ecf0f1",
        COLOR_TEXT_PRIMARY: "#2c3e50",
        COLOR_TEXT_SECONDARY: "#95a5a6",
        COLOR_ERROR: "#e74c3c",
        COLOR_WARNING: "#f39c12",
        COLOR_SUCCESS: "#2ecc71",
        COLOR_GREY_DARK: "#7E7E7E",
        COLOR_GREY_LIGHT: "#E0E0E0",
        COLOR_BEIGE: "#F7F2E8",
        COLOR_ORANGE: "#D05F33",
        COLOR_DARK_BROWN: "#262123",
        COLOR_LIGHT_YELLOW: "#FFFFE4",
        COLOR_SEMI_TRANSPARENT_BLACK: "rgba(0, 0, 0, 0.5)",
        AQUA_GREEN: "#1A5276",
        RED: "#B03A2E",
        PURPLE: "#8E44AD",
        GRAY: "#898A8D",
        GREEN: "#229954",
        BLUE: "#2471A3",
        YELLOW: "#F4D03F",
        WHITE: "#FFFFFF",
        BLACK: "#000000",
        LIGHT_GRAY: "#D3D3D3",
        DARK_GRAY: "#A9A9A9",
        TRANSPARENT: "transparent",
        LIGHT_BLUE: "#ADD8E6",
        LIGHT_GREEN: "#90EE90",
        LIGHT_YELLOW: "#FFFFE0",
        LIGHT_RED: "#F08080",
        LIGHT_PURPLE: "#E6E6FA",
        LIGHT_ORANGE: "#FFA07A",
        LIGHT_PINK: "#FFB6C1",
        LIGHT_BROWN: "#CD853F",
        LIGHT_CYAN: "#E0FFFF",
        LIGHT_MAGENTA: "#FFC0CB",
        LIGHT_GOLDENROD_YELLOW: "#FAFAD2",
        LIGHT_CORAL: "#F08080",
        LIGHT_AQUA: "#00FFFF",
        LIGHT_LIME: "#32CD32",
        LIGHT_TURQUOISE: "#40E0D0",
        LIGHT_INDIGO: "#4B0082"
    }