// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/onboarding/rpc_requests.proto" (package "onboarding", syntax proto3)
// tslint:disable
import type {BinaryWriteOptions} from '@protobuf-ts/runtime';
import type {IBinaryWriter} from '@protobuf-ts/runtime';
import {WireType} from '@protobuf-ts/runtime';
import type {BinaryReadOptions} from '@protobuf-ts/runtime';
import type {IBinaryReader} from '@protobuf-ts/runtime';
import {UnknownFieldHandler} from '@protobuf-ts/runtime';
import type {PartialMessage} from '@protobuf-ts/runtime';
import {reflectionMergePartial} from '@protobuf-ts/runtime';
import {MessageType} from '@protobuf-ts/runtime';
import {Timestamp} from '../../google/protobuf/timestamp';
import {RequestHeader} from '../../core/headers';
/**
 * @generated from protobuf message onboarding.TriggerPhoneOTPVerificationRequest
 */
export interface TriggerPhoneOTPVerificationRequest {
  /**
   * @generated from protobuf field: core.RequestHeader req_header = 1;
   */
  reqHeader?: RequestHeader;
  /**
   * @generated from protobuf field: string otp = 2;
   */
  otp: string;
}
/**
 * @generated from protobuf message onboarding.TriggerEmailVerificationRequest
 */
export interface TriggerEmailVerificationRequest {
  /**
   * @generated from protobuf field: core.RequestHeader req_header = 1;
   */
  reqHeader?: RequestHeader;
  /**
   * @generated from protobuf field: string email_id = 2;
   */
  emailId: string;
  /**
   * @generated from protobuf field: string user_name = 3;
   */
  userName: string;
}
/**
 * @generated from protobuf message onboarding.TriggerPanVerificationRequest
 */
export interface TriggerPanVerificationRequest {
  /**
   * @generated from protobuf field: core.RequestHeader req_header = 1;
   */
  reqHeader?: RequestHeader;
  /**
   * @generated from protobuf field: string pan_number = 2;
   */
  panNumber: string;
  /**
   * @generated from protobuf field: google.protobuf.Timestamp date_of_birth = 3;
   */
  dateOfBirth?: Timestamp;
}
/**
 * @generated from protobuf message onboarding.TriggerLivenessCheckRequest
 */
export interface TriggerLivenessCheckRequest {
  /**
   * @generated from protobuf field: core.RequestHeader req_header = 1;
   */
  reqHeader?: RequestHeader;
  /**
   * @generated from protobuf field: string otp_spoken = 2;
   */
  otpSpoken: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class TriggerPhoneOTPVerificationRequest$Type extends MessageType<TriggerPhoneOTPVerificationRequest> {
  constructor() {
    super('onboarding.TriggerPhoneOTPVerificationRequest', [
      {no: 1, name: 'req_header', kind: 'message', T: () => RequestHeader},
      {no: 2, name: 'otp', kind: 'scalar', T: 9 /*ScalarType.STRING*/},
    ]);
  }
  create(
    value?: PartialMessage<TriggerPhoneOTPVerificationRequest>,
  ): TriggerPhoneOTPVerificationRequest {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.otp = '';
    if (value !== undefined)
      reflectionMergePartial<TriggerPhoneOTPVerificationRequest>(
        this,
        message,
        value,
      );
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: TriggerPhoneOTPVerificationRequest,
  ): TriggerPhoneOTPVerificationRequest {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* core.RequestHeader req_header */ 1:
          message.reqHeader = RequestHeader.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.reqHeader,
          );
          break;
        case /* string otp */ 2:
          message.otp = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: TriggerPhoneOTPVerificationRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* core.RequestHeader req_header = 1; */
    if (message.reqHeader)
      RequestHeader.internalBinaryWrite(
        message.reqHeader,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string otp = 2; */
    if (message.otp !== '')
      writer.tag(2, WireType.LengthDelimited).string(message.otp);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message onboarding.TriggerPhoneOTPVerificationRequest
 */
export const TriggerPhoneOTPVerificationRequest =
  new TriggerPhoneOTPVerificationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerEmailVerificationRequest$Type extends MessageType<TriggerEmailVerificationRequest> {
  constructor() {
    super('onboarding.TriggerEmailVerificationRequest', [
      {no: 1, name: 'req_header', kind: 'message', T: () => RequestHeader},
      {no: 2, name: 'email_id', kind: 'scalar', T: 9 /*ScalarType.STRING*/},
      {no: 3, name: 'user_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/},
    ]);
  }
  create(
    value?: PartialMessage<TriggerEmailVerificationRequest>,
  ): TriggerEmailVerificationRequest {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.emailId = '';
    message.userName = '';
    if (value !== undefined)
      reflectionMergePartial<TriggerEmailVerificationRequest>(
        this,
        message,
        value,
      );
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: TriggerEmailVerificationRequest,
  ): TriggerEmailVerificationRequest {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* core.RequestHeader req_header */ 1:
          message.reqHeader = RequestHeader.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.reqHeader,
          );
          break;
        case /* string email_id */ 2:
          message.emailId = reader.string();
          break;
        case /* string user_name */ 3:
          message.userName = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: TriggerEmailVerificationRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* core.RequestHeader req_header = 1; */
    if (message.reqHeader)
      RequestHeader.internalBinaryWrite(
        message.reqHeader,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string email_id = 2; */
    if (message.emailId !== '')
      writer.tag(2, WireType.LengthDelimited).string(message.emailId);
    /* string user_name = 3; */
    if (message.userName !== '')
      writer.tag(3, WireType.LengthDelimited).string(message.userName);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message onboarding.TriggerEmailVerificationRequest
 */
export const TriggerEmailVerificationRequest =
  new TriggerEmailVerificationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerPanVerificationRequest$Type extends MessageType<TriggerPanVerificationRequest> {
  constructor() {
    super('onboarding.TriggerPanVerificationRequest', [
      {no: 1, name: 'req_header', kind: 'message', T: () => RequestHeader},
      {no: 2, name: 'pan_number', kind: 'scalar', T: 9 /*ScalarType.STRING*/},
      {no: 3, name: 'date_of_birth', kind: 'message', T: () => Timestamp},
    ]);
  }
  create(
    value?: PartialMessage<TriggerPanVerificationRequest>,
  ): TriggerPanVerificationRequest {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.panNumber = '';
    if (value !== undefined)
      reflectionMergePartial<TriggerPanVerificationRequest>(
        this,
        message,
        value,
      );
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: TriggerPanVerificationRequest,
  ): TriggerPanVerificationRequest {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* core.RequestHeader req_header */ 1:
          message.reqHeader = RequestHeader.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.reqHeader,
          );
          break;
        case /* string pan_number */ 2:
          message.panNumber = reader.string();
          break;
        case /* google.protobuf.Timestamp date_of_birth */ 3:
          message.dateOfBirth = Timestamp.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.dateOfBirth,
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: TriggerPanVerificationRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* core.RequestHeader req_header = 1; */
    if (message.reqHeader)
      RequestHeader.internalBinaryWrite(
        message.reqHeader,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string pan_number = 2; */
    if (message.panNumber !== '')
      writer.tag(2, WireType.LengthDelimited).string(message.panNumber);
    /* google.protobuf.Timestamp date_of_birth = 3; */
    if (message.dateOfBirth)
      Timestamp.internalBinaryWrite(
        message.dateOfBirth,
        writer.tag(3, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message onboarding.TriggerPanVerificationRequest
 */
export const TriggerPanVerificationRequest =
  new TriggerPanVerificationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerLivenessCheckRequest$Type extends MessageType<TriggerLivenessCheckRequest> {
  constructor() {
    super('onboarding.TriggerLivenessCheckRequest', [
      {no: 1, name: 'req_header', kind: 'message', T: () => RequestHeader},
      {no: 2, name: 'otp_spoken', kind: 'scalar', T: 9 /*ScalarType.STRING*/},
    ]);
  }
  create(
    value?: PartialMessage<TriggerLivenessCheckRequest>,
  ): TriggerLivenessCheckRequest {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.otpSpoken = '';
    if (value !== undefined)
      reflectionMergePartial<TriggerLivenessCheckRequest>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: TriggerLivenessCheckRequest,
  ): TriggerLivenessCheckRequest {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* core.RequestHeader req_header */ 1:
          message.reqHeader = RequestHeader.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.reqHeader,
          );
          break;
        case /* string otp_spoken */ 2:
          message.otpSpoken = reader.string();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: TriggerLivenessCheckRequest,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* core.RequestHeader req_header = 1; */
    if (message.reqHeader)
      RequestHeader.internalBinaryWrite(
        message.reqHeader,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string otp_spoken = 2; */
    if (message.otpSpoken !== '')
      writer.tag(2, WireType.LengthDelimited).string(message.otpSpoken);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message onboarding.TriggerLivenessCheckRequest
 */
export const TriggerLivenessCheckRequest =
  new TriggerLivenessCheckRequest$Type();
