// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/onboarding/screen_options.proto" (package "onboarding", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { HorizontalIconText } from "../ui/horizontal_icon_text";
import { Timestamp } from "../../google/protobuf/timestamp";
import { ErrorType } from "../enums/response_types";
import { Modal } from "../ui/Modal";
import { CheckBox } from "../ui/CheckBox";
import { Button } from "../ui/Button";
import { LocationConsent } from "../ui/LocationConsent";
import { NotificationsConsent } from "../ui/NotificationsConsent";
import { Text } from "../ui/Text";
import { Image } from "../ui/Image";
import { ResponseHeader } from "../../core/headers";
/**
 * @generated from protobuf message onboarding.OtherConsentsScreen
 */
export interface OtherConsentsScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * Image to display on the permission screen
     *
     * @generated from protobuf field: ui.Image permission_image = 2;
     */
    permissionImage?: Image;
    /**
     * Header text to display on the permission screen
     *
     * @generated from protobuf field: ui.Text permission_header = 3;
     */
    permissionHeader?: Text;
    /**
     * Paragraph text to display on the permission screen
     *
     * @generated from protobuf field: ui.Text permission_paragraph = 4;
     */
    permissionParagraph?: Text;
    /**
     * Notifications consent component
     *
     * @generated from protobuf field: ui.NotificationsConsent notifications_consent = 5;
     */
    notificationsConsent?: NotificationsConsent;
    /**
     * Location consent component
     *
     * @generated from protobuf field: ui.LocationConsent location_consent = 6;
     */
    locationConsent?: LocationConsent;
    /**
     * Next button component
     *
     * @generated from protobuf field: ui.Button next_button = 7;
     */
    nextButton?: Button;
    /**
     * Agreement checkbox component
     *
     * @generated from protobuf field: ui.CheckBox agreement_checkbox = 8;
     */
    agreementCheckbox?: CheckBox;
    /**
     * Alert modal component
     *
     * @generated from protobuf field: ui.Modal alert_modal = 9;
     */
    alertModal?: Modal;
    /**
     * Error type (if any)
     *
     * @generated from protobuf field: enums.ErrorType error = 10;
     */
    error: ErrorType;
}
/**
 * @generated from protobuf message onboarding.BiometricConsentScreen
 */
export interface BiometricConsentScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * @generated from protobuf field: ui.Image top_image = 2;
     */
    topImage?: Image;
    /**
     * @generated from protobuf field: ui.Text header = 3;
     */
    header?: Text;
    /**
     * @generated from protobuf field: ui.Text top_text = 4;
     */
    topText?: Text;
    /**
     * @generated from protobuf field: ui.Image lock_icon = 5;
     */
    lockIcon?: Image;
    /**
     * @generated from protobuf field: ui.Text paragraph_text = 6;
     */
    paragraphText?: Text;
    /**
     * @generated from protobuf field: ui.Button primary_button = 7;
     */
    primaryButton?: Button;
    /**
     * @generated from protobuf field: enums.ErrorType error_code = 8;
     */
    errorCode: ErrorType;
}
/**
 * @generated from protobuf message onboarding.LivenessCheckScreen
 */
export interface LivenessCheckScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * @generated from protobuf field: string otp_to_show = 2;
     */
    otpToShow: string;
    /**
     * @generated from protobuf field: ui.Button next_button = 3;
     */
    nextButton?: Button;
}
/**
 * @generated from protobuf message onboarding.PanVerificationScreen
 */
export interface PanVerificationScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * @generated from protobuf field: string image_url = 2;
     */
    imageUrl: string;
    /**
     * @generated from protobuf field: string title = 3;
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 4;
     */
    description: string;
    /**
     * @generated from protobuf field: string pan_number = 5;
     */
    panNumber: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp date_of_birth = 6;
     */
    dateOfBirth?: Timestamp;
    /**
     * @generated from protobuf field: string details_storage_permission_text = 7;
     */
    detailsStoragePermissionText: string;
    /**
     * @generated from protobuf field: string info_usage_permission_text = 8;
     */
    infoUsagePermissionText: string;
    /**
     * @generated from protobuf field: ui.Button next_button = 9;
     */
    nextButton?: Button;
    /**
     * @generated from protobuf field: string no_pan_text = 10;
     */
    noPanText: string;
}
/**
 * @generated from protobuf message onboarding.PhoneVerificationScreen
 */
export interface PhoneVerificationScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * @generated from protobuf field: ui.Text title = 2;
     */
    title?: Text;
    /**
     * @generated from protobuf field: string sub_title = 3;
     */
    subTitle: string;
    /**
     * @generated from protobuf field: string phone_number_heading = 4;
     */
    phoneNumberHeading: string;
    /**
     * @generated from protobuf field: string input_number = 5;
     */
    inputNumber: string;
    /**
     * @generated from protobuf field: string phone_number_briefing = 6;
     */
    phoneNumberBriefing: string;
    /**
     * @generated from protobuf field: string img1_url = 7;
     */
    img1Url: string;
    /**
     * @generated from protobuf field: ui.Button primary_button = 8;
     */
    primaryButton?: Button;
}
/**
 * @generated from protobuf message onboarding.PhoneOTPScreen
 */
export interface PhoneOTPScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * @generated from protobuf field: string wait_text = 4;
     */
    waitText: string;
    /**
     * @generated from protobuf field: int32 timer_in_seconds = 5;
     */
    timerInSeconds: number;
    /**
     * @generated from protobuf field: string resend_otp_text = 6;
     */
    resendOtpText: string;
    /**
     * @generated from protobuf field: ui.Button primary_button = 7;
     */
    primaryButton?: Button;
}
/**
 * @generated from protobuf message onboarding.EmailVerificationScreen
 */
export interface EmailVerificationScreen {
    /**
     * @generated from protobuf field: core.ResponseHeader resp_header = 1;
     */
    respHeader?: ResponseHeader;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string sub_title = 3;
     */
    subTitle: string;
    /**
     * @generated from protobuf field: ui.Button primary_button = 4;
     */
    primaryButton?: Button;
    /**
     * @generated from protobuf field: string img_url = 5;
     */
    imgUrl: string;
}
/**
 * @generated from protobuf message onboarding.TermsConditionsScreen
 */
export interface TermsConditionsScreen {
    /**
     * @generated from protobuf field: ui.Image top_image = 1;
     */
    topImage?: Image;
    /**
     * @generated from protobuf field: ui.Text title = 2;
     */
    title?: Text;
    /**
     * @generated from protobuf field: ui.Text subtitle = 3;
     */
    subtitle?: Text;
    /**
     * @generated from protobuf field: repeated ui.HorizontalIconText horizontal_component = 4;
     */
    horizontalComponent: HorizontalIconText[];
    /**
     * @generated from protobuf field: ui.Button next_button = 5;
     */
    nextButton?: Button;
    /**
     * @generated from protobuf field: ui.CheckBox agreement_checkbox = 6;
     */
    agreementCheckbox?: CheckBox;
    /**
     * @generated from protobuf field: ui.CheckBox data_sharing_checkbox = 7;
     */
    dataSharingCheckbox?: CheckBox;
    /**
     * @generated from protobuf field: ui.Modal alert_modal = 8;
     */
    alertModal?: Modal;
}
// @generated message type with reflection information, may provide speed optimized methods
class OtherConsentsScreen$Type extends MessageType<OtherConsentsScreen> {
    constructor() {
        super("onboarding.OtherConsentsScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "permission_image", kind: "message", T: () => Image },
            { no: 3, name: "permission_header", kind: "message", T: () => Text },
            { no: 4, name: "permission_paragraph", kind: "message", T: () => Text },
            { no: 5, name: "notifications_consent", kind: "message", T: () => NotificationsConsent },
            { no: 6, name: "location_consent", kind: "message", T: () => LocationConsent },
            { no: 7, name: "next_button", kind: "message", T: () => Button },
            { no: 8, name: "agreement_checkbox", kind: "message", T: () => CheckBox },
            { no: 9, name: "alert_modal", kind: "message", T: () => Modal },
            { no: 10, name: "error", kind: "enum", T: () => ["enums.ErrorType", ErrorType] }
        ]);
    }
    create(value?: PartialMessage<OtherConsentsScreen>): OtherConsentsScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.error = 0;
        if (value !== undefined)
            reflectionMergePartial<OtherConsentsScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OtherConsentsScreen): OtherConsentsScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* ui.Image permission_image */ 2:
                    message.permissionImage = Image.internalBinaryRead(reader, reader.uint32(), options, message.permissionImage);
                    break;
                case /* ui.Text permission_header */ 3:
                    message.permissionHeader = Text.internalBinaryRead(reader, reader.uint32(), options, message.permissionHeader);
                    break;
                case /* ui.Text permission_paragraph */ 4:
                    message.permissionParagraph = Text.internalBinaryRead(reader, reader.uint32(), options, message.permissionParagraph);
                    break;
                case /* ui.NotificationsConsent notifications_consent */ 5:
                    message.notificationsConsent = NotificationsConsent.internalBinaryRead(reader, reader.uint32(), options, message.notificationsConsent);
                    break;
                case /* ui.LocationConsent location_consent */ 6:
                    message.locationConsent = LocationConsent.internalBinaryRead(reader, reader.uint32(), options, message.locationConsent);
                    break;
                case /* ui.Button next_button */ 7:
                    message.nextButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.nextButton);
                    break;
                case /* ui.CheckBox agreement_checkbox */ 8:
                    message.agreementCheckbox = CheckBox.internalBinaryRead(reader, reader.uint32(), options, message.agreementCheckbox);
                    break;
                case /* ui.Modal alert_modal */ 9:
                    message.alertModal = Modal.internalBinaryRead(reader, reader.uint32(), options, message.alertModal);
                    break;
                case /* enums.ErrorType error */ 10:
                    message.error = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OtherConsentsScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ui.Image permission_image = 2; */
        if (message.permissionImage)
            Image.internalBinaryWrite(message.permissionImage, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text permission_header = 3; */
        if (message.permissionHeader)
            Text.internalBinaryWrite(message.permissionHeader, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text permission_paragraph = 4; */
        if (message.permissionParagraph)
            Text.internalBinaryWrite(message.permissionParagraph, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* ui.NotificationsConsent notifications_consent = 5; */
        if (message.notificationsConsent)
            NotificationsConsent.internalBinaryWrite(message.notificationsConsent, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* ui.LocationConsent location_consent = 6; */
        if (message.locationConsent)
            LocationConsent.internalBinaryWrite(message.locationConsent, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* ui.Button next_button = 7; */
        if (message.nextButton)
            Button.internalBinaryWrite(message.nextButton, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* ui.CheckBox agreement_checkbox = 8; */
        if (message.agreementCheckbox)
            CheckBox.internalBinaryWrite(message.agreementCheckbox, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* ui.Modal alert_modal = 9; */
        if (message.alertModal)
            Modal.internalBinaryWrite(message.alertModal, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* enums.ErrorType error = 10; */
        if (message.error !== 0)
            writer.tag(10, WireType.Varint).int32(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.OtherConsentsScreen
 */
export const OtherConsentsScreen = new OtherConsentsScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BiometricConsentScreen$Type extends MessageType<BiometricConsentScreen> {
    constructor() {
        super("onboarding.BiometricConsentScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "top_image", kind: "message", T: () => Image },
            { no: 3, name: "header", kind: "message", T: () => Text },
            { no: 4, name: "top_text", kind: "message", T: () => Text },
            { no: 5, name: "lock_icon", kind: "message", T: () => Image },
            { no: 6, name: "paragraph_text", kind: "message", T: () => Text },
            { no: 7, name: "primary_button", kind: "message", T: () => Button },
            { no: 8, name: "error_code", kind: "enum", T: () => ["enums.ErrorType", ErrorType] }
        ]);
    }
    create(value?: PartialMessage<BiometricConsentScreen>): BiometricConsentScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.errorCode = 0;
        if (value !== undefined)
            reflectionMergePartial<BiometricConsentScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BiometricConsentScreen): BiometricConsentScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* ui.Image top_image */ 2:
                    message.topImage = Image.internalBinaryRead(reader, reader.uint32(), options, message.topImage);
                    break;
                case /* ui.Text header */ 3:
                    message.header = Text.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* ui.Text top_text */ 4:
                    message.topText = Text.internalBinaryRead(reader, reader.uint32(), options, message.topText);
                    break;
                case /* ui.Image lock_icon */ 5:
                    message.lockIcon = Image.internalBinaryRead(reader, reader.uint32(), options, message.lockIcon);
                    break;
                case /* ui.Text paragraph_text */ 6:
                    message.paragraphText = Text.internalBinaryRead(reader, reader.uint32(), options, message.paragraphText);
                    break;
                case /* ui.Button primary_button */ 7:
                    message.primaryButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.primaryButton);
                    break;
                case /* enums.ErrorType error_code */ 8:
                    message.errorCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BiometricConsentScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ui.Image top_image = 2; */
        if (message.topImage)
            Image.internalBinaryWrite(message.topImage, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text header = 3; */
        if (message.header)
            Text.internalBinaryWrite(message.header, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text top_text = 4; */
        if (message.topText)
            Text.internalBinaryWrite(message.topText, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* ui.Image lock_icon = 5; */
        if (message.lockIcon)
            Image.internalBinaryWrite(message.lockIcon, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text paragraph_text = 6; */
        if (message.paragraphText)
            Text.internalBinaryWrite(message.paragraphText, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* ui.Button primary_button = 7; */
        if (message.primaryButton)
            Button.internalBinaryWrite(message.primaryButton, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* enums.ErrorType error_code = 8; */
        if (message.errorCode !== 0)
            writer.tag(8, WireType.Varint).int32(message.errorCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.BiometricConsentScreen
 */
export const BiometricConsentScreen = new BiometricConsentScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LivenessCheckScreen$Type extends MessageType<LivenessCheckScreen> {
    constructor() {
        super("onboarding.LivenessCheckScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "otp_to_show", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "next_button", kind: "message", T: () => Button }
        ]);
    }
    create(value?: PartialMessage<LivenessCheckScreen>): LivenessCheckScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.otpToShow = "";
        if (value !== undefined)
            reflectionMergePartial<LivenessCheckScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LivenessCheckScreen): LivenessCheckScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* string otp_to_show */ 2:
                    message.otpToShow = reader.string();
                    break;
                case /* ui.Button next_button */ 3:
                    message.nextButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.nextButton);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LivenessCheckScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string otp_to_show = 2; */
        if (message.otpToShow !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.otpToShow);
        /* ui.Button next_button = 3; */
        if (message.nextButton)
            Button.internalBinaryWrite(message.nextButton, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.LivenessCheckScreen
 */
export const LivenessCheckScreen = new LivenessCheckScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PanVerificationScreen$Type extends MessageType<PanVerificationScreen> {
    constructor() {
        super("onboarding.PanVerificationScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "image_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "pan_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "date_of_birth", kind: "message", T: () => Timestamp },
            { no: 7, name: "details_storage_permission_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "info_usage_permission_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "next_button", kind: "message", T: () => Button },
            { no: 10, name: "no_pan_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PanVerificationScreen>): PanVerificationScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.imageUrl = "";
        message.title = "";
        message.description = "";
        message.panNumber = "";
        message.detailsStoragePermissionText = "";
        message.infoUsagePermissionText = "";
        message.noPanText = "";
        if (value !== undefined)
            reflectionMergePartial<PanVerificationScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PanVerificationScreen): PanVerificationScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* string image_url */ 2:
                    message.imageUrl = reader.string();
                    break;
                case /* string title */ 3:
                    message.title = reader.string();
                    break;
                case /* string description */ 4:
                    message.description = reader.string();
                    break;
                case /* string pan_number */ 5:
                    message.panNumber = reader.string();
                    break;
                case /* google.protobuf.Timestamp date_of_birth */ 6:
                    message.dateOfBirth = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.dateOfBirth);
                    break;
                case /* string details_storage_permission_text */ 7:
                    message.detailsStoragePermissionText = reader.string();
                    break;
                case /* string info_usage_permission_text */ 8:
                    message.infoUsagePermissionText = reader.string();
                    break;
                case /* ui.Button next_button */ 9:
                    message.nextButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.nextButton);
                    break;
                case /* string no_pan_text */ 10:
                    message.noPanText = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PanVerificationScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string image_url = 2; */
        if (message.imageUrl !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.imageUrl);
        /* string title = 3; */
        if (message.title !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.title);
        /* string description = 4; */
        if (message.description !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.description);
        /* string pan_number = 5; */
        if (message.panNumber !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.panNumber);
        /* google.protobuf.Timestamp date_of_birth = 6; */
        if (message.dateOfBirth)
            Timestamp.internalBinaryWrite(message.dateOfBirth, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string details_storage_permission_text = 7; */
        if (message.detailsStoragePermissionText !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.detailsStoragePermissionText);
        /* string info_usage_permission_text = 8; */
        if (message.infoUsagePermissionText !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.infoUsagePermissionText);
        /* ui.Button next_button = 9; */
        if (message.nextButton)
            Button.internalBinaryWrite(message.nextButton, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* string no_pan_text = 10; */
        if (message.noPanText !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.noPanText);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.PanVerificationScreen
 */
export const PanVerificationScreen = new PanVerificationScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PhoneVerificationScreen$Type extends MessageType<PhoneVerificationScreen> {
    constructor() {
        super("onboarding.PhoneVerificationScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "title", kind: "message", T: () => Text },
            { no: 3, name: "sub_title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "phone_number_heading", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "input_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "phone_number_briefing", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "img1_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "primary_button", kind: "message", T: () => Button }
        ]);
    }
    create(value?: PartialMessage<PhoneVerificationScreen>): PhoneVerificationScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.subTitle = "";
        message.phoneNumberHeading = "";
        message.inputNumber = "";
        message.phoneNumberBriefing = "";
        message.img1Url = "";
        if (value !== undefined)
            reflectionMergePartial<PhoneVerificationScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PhoneVerificationScreen): PhoneVerificationScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* ui.Text title */ 2:
                    message.title = Text.internalBinaryRead(reader, reader.uint32(), options, message.title);
                    break;
                case /* string sub_title */ 3:
                    message.subTitle = reader.string();
                    break;
                case /* string phone_number_heading */ 4:
                    message.phoneNumberHeading = reader.string();
                    break;
                case /* string input_number */ 5:
                    message.inputNumber = reader.string();
                    break;
                case /* string phone_number_briefing */ 6:
                    message.phoneNumberBriefing = reader.string();
                    break;
                case /* string img1_url */ 7:
                    message.img1Url = reader.string();
                    break;
                case /* ui.Button primary_button */ 8:
                    message.primaryButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.primaryButton);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PhoneVerificationScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text title = 2; */
        if (message.title)
            Text.internalBinaryWrite(message.title, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string sub_title = 3; */
        if (message.subTitle !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.subTitle);
        /* string phone_number_heading = 4; */
        if (message.phoneNumberHeading !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.phoneNumberHeading);
        /* string input_number = 5; */
        if (message.inputNumber !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.inputNumber);
        /* string phone_number_briefing = 6; */
        if (message.phoneNumberBriefing !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.phoneNumberBriefing);
        /* string img1_url = 7; */
        if (message.img1Url !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.img1Url);
        /* ui.Button primary_button = 8; */
        if (message.primaryButton)
            Button.internalBinaryWrite(message.primaryButton, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.PhoneVerificationScreen
 */
export const PhoneVerificationScreen = new PhoneVerificationScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PhoneOTPScreen$Type extends MessageType<PhoneOTPScreen> {
    constructor() {
        super("onboarding.PhoneOTPScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "wait_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "timer_in_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "resend_otp_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "primary_button", kind: "message", T: () => Button }
        ]);
    }
    create(value?: PartialMessage<PhoneOTPScreen>): PhoneOTPScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.description = "";
        message.waitText = "";
        message.timerInSeconds = 0;
        message.resendOtpText = "";
        if (value !== undefined)
            reflectionMergePartial<PhoneOTPScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PhoneOTPScreen): PhoneOTPScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string wait_text */ 4:
                    message.waitText = reader.string();
                    break;
                case /* int32 timer_in_seconds */ 5:
                    message.timerInSeconds = reader.int32();
                    break;
                case /* string resend_otp_text */ 6:
                    message.resendOtpText = reader.string();
                    break;
                case /* ui.Button primary_button */ 7:
                    message.primaryButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.primaryButton);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PhoneOTPScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string wait_text = 4; */
        if (message.waitText !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.waitText);
        /* int32 timer_in_seconds = 5; */
        if (message.timerInSeconds !== 0)
            writer.tag(5, WireType.Varint).int32(message.timerInSeconds);
        /* string resend_otp_text = 6; */
        if (message.resendOtpText !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.resendOtpText);
        /* ui.Button primary_button = 7; */
        if (message.primaryButton)
            Button.internalBinaryWrite(message.primaryButton, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.PhoneOTPScreen
 */
export const PhoneOTPScreen = new PhoneOTPScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EmailVerificationScreen$Type extends MessageType<EmailVerificationScreen> {
    constructor() {
        super("onboarding.EmailVerificationScreen", [
            { no: 1, name: "resp_header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "sub_title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "primary_button", kind: "message", T: () => Button },
            { no: 5, name: "img_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<EmailVerificationScreen>): EmailVerificationScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.subTitle = "";
        message.imgUrl = "";
        if (value !== undefined)
            reflectionMergePartial<EmailVerificationScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EmailVerificationScreen): EmailVerificationScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* core.ResponseHeader resp_header */ 1:
                    message.respHeader = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.respHeader);
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string sub_title */ 3:
                    message.subTitle = reader.string();
                    break;
                case /* ui.Button primary_button */ 4:
                    message.primaryButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.primaryButton);
                    break;
                case /* string img_url */ 5:
                    message.imgUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EmailVerificationScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* core.ResponseHeader resp_header = 1; */
        if (message.respHeader)
            ResponseHeader.internalBinaryWrite(message.respHeader, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string sub_title = 3; */
        if (message.subTitle !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.subTitle);
        /* ui.Button primary_button = 4; */
        if (message.primaryButton)
            Button.internalBinaryWrite(message.primaryButton, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string img_url = 5; */
        if (message.imgUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.imgUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.EmailVerificationScreen
 */
export const EmailVerificationScreen = new EmailVerificationScreen$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TermsConditionsScreen$Type extends MessageType<TermsConditionsScreen> {
    constructor() {
        super("onboarding.TermsConditionsScreen", [
            { no: 1, name: "top_image", kind: "message", T: () => Image },
            { no: 2, name: "title", kind: "message", T: () => Text },
            { no: 3, name: "subtitle", kind: "message", T: () => Text },
            { no: 4, name: "horizontal_component", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => HorizontalIconText },
            { no: 5, name: "next_button", kind: "message", T: () => Button },
            { no: 6, name: "agreement_checkbox", kind: "message", T: () => CheckBox },
            { no: 7, name: "data_sharing_checkbox", kind: "message", T: () => CheckBox },
            { no: 8, name: "alert_modal", kind: "message", T: () => Modal }
        ]);
    }
    create(value?: PartialMessage<TermsConditionsScreen>): TermsConditionsScreen {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.horizontalComponent = [];
        if (value !== undefined)
            reflectionMergePartial<TermsConditionsScreen>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TermsConditionsScreen): TermsConditionsScreen {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* ui.Image top_image */ 1:
                    message.topImage = Image.internalBinaryRead(reader, reader.uint32(), options, message.topImage);
                    break;
                case /* ui.Text title */ 2:
                    message.title = Text.internalBinaryRead(reader, reader.uint32(), options, message.title);
                    break;
                case /* ui.Text subtitle */ 3:
                    message.subtitle = Text.internalBinaryRead(reader, reader.uint32(), options, message.subtitle);
                    break;
                case /* repeated ui.HorizontalIconText horizontal_component */ 4:
                    message.horizontalComponent.push(HorizontalIconText.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* ui.Button next_button */ 5:
                    message.nextButton = Button.internalBinaryRead(reader, reader.uint32(), options, message.nextButton);
                    break;
                case /* ui.CheckBox agreement_checkbox */ 6:
                    message.agreementCheckbox = CheckBox.internalBinaryRead(reader, reader.uint32(), options, message.agreementCheckbox);
                    break;
                case /* ui.CheckBox data_sharing_checkbox */ 7:
                    message.dataSharingCheckbox = CheckBox.internalBinaryRead(reader, reader.uint32(), options, message.dataSharingCheckbox);
                    break;
                case /* ui.Modal alert_modal */ 8:
                    message.alertModal = Modal.internalBinaryRead(reader, reader.uint32(), options, message.alertModal);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TermsConditionsScreen, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* ui.Image top_image = 1; */
        if (message.topImage)
            Image.internalBinaryWrite(message.topImage, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text title = 2; */
        if (message.title)
            Text.internalBinaryWrite(message.title, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* ui.Text subtitle = 3; */
        if (message.subtitle)
            Text.internalBinaryWrite(message.subtitle, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated ui.HorizontalIconText horizontal_component = 4; */
        for (let i = 0; i < message.horizontalComponent.length; i++)
            HorizontalIconText.internalBinaryWrite(message.horizontalComponent[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* ui.Button next_button = 5; */
        if (message.nextButton)
            Button.internalBinaryWrite(message.nextButton, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* ui.CheckBox agreement_checkbox = 6; */
        if (message.agreementCheckbox)
            CheckBox.internalBinaryWrite(message.agreementCheckbox, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* ui.CheckBox data_sharing_checkbox = 7; */
        if (message.dataSharingCheckbox)
            CheckBox.internalBinaryWrite(message.dataSharingCheckbox, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* ui.Modal alert_modal = 8; */
        if (message.alertModal)
            Modal.internalBinaryWrite(message.alertModal, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message onboarding.TermsConditionsScreen
 */
export const TermsConditionsScreen = new TermsConditionsScreen$Type();
