// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.0
// source: protos-frontend/UI/Button.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { CornerRadius } from "./ServerDrivenMessages";
import { Text } from "./Text";

export const protobufPackage = "UI";

/** Define a message structure for a Button. */
export interface Button {
  /** The text displayed on the button. */
  text:
    | Text
    | undefined;
  /** The corner radius of the button. */
  cornerRadius:
    | CornerRadius
    | undefined;
  /** The background color of the button. */
  backgroundColor: string;
}

function createBaseButton(): Button {
  return { text: undefined, cornerRadius: undefined, backgroundColor: "" };
}

export const Button = {
  encode(message: Button, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.text !== undefined) {
      Text.encode(message.text, writer.uint32(10).fork()).ldelim();
    }
    if (message.cornerRadius !== undefined) {
      CornerRadius.encode(message.cornerRadius, writer.uint32(18).fork()).ldelim();
    }
    if (message.backgroundColor !== "") {
      writer.uint32(26).string(message.backgroundColor);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Button {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseButton();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.text = Text.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.cornerRadius = CornerRadius.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.backgroundColor = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Button {
    return {
      text: isSet(object.text) ? Text.fromJSON(object.text) : undefined,
      cornerRadius: isSet(object.cornerRadius) ? CornerRadius.fromJSON(object.cornerRadius) : undefined,
      backgroundColor: isSet(object.backgroundColor) ? globalThis.String(object.backgroundColor) : "",
    };
  },

  toJSON(message: Button): unknown {
    const obj: any = {};
    if (message.text !== undefined) {
      obj.text = Text.toJSON(message.text);
    }
    if (message.cornerRadius !== undefined) {
      obj.cornerRadius = CornerRadius.toJSON(message.cornerRadius);
    }
    if (message.backgroundColor !== "") {
      obj.backgroundColor = message.backgroundColor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Button>, I>>(base?: I): Button {
    return Button.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Button>, I>>(object: I): Button {
    const message = createBaseButton();
    message.text = (object.text !== undefined && object.text !== null) ? Text.fromPartial(object.text) : undefined;
    message.cornerRadius = (object.cornerRadius !== undefined && object.cornerRadius !== null)
      ? CornerRadius.fromPartial(object.cornerRadius)
      : undefined;
    message.backgroundColor = object.backgroundColor ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
