// Define your error string constants
export const NETWORK_ERROR = "Unable to connect. Please check your network connection.";
export const LOGIN_FAILED = "Login failed. Please check your credentials and try again.";
export const SIGNUP_FAILED = "Sign up failed. Please try again later.";
export const UNEXPECTED_ERROR = "An unexpected error occurred. Please try again.";
export const INVALID_EMAIL = "Please enter a valid email address.";
export const PASSWORD_TOO_SHORT = "Password must be at least 6 characters long.";
export const USER_NOT_FOUND = "User not found. Please check the entered details.";
export const EMAIL_ALREADY_IN_USE = "This email is already in use. Please use a different email.";
export const FIELD_REQUIRED = "This field is required.";
export const INVALID_PHONE_NUMBER = "Please enter a valid phone number.";
export const INVALID_OTP = "Invalid OTP. Please try again.";
export const OTP_EXPIRED = "OTP has expired. Please request a new one.";
export const INVALID_PASSWORD = "Invalid password. Please try again.";
export const INVALID_NAME = "Please enter a valid name.";
export const INVALID_USERNAME = "Please enter a valid username."; 
export const INVALID_EMAIL_OR_PASSWORD = "Invalid email or password. Please try again.";
export const INVALID_PHONE_NUMBER_OR_PASSWORD = "Invalid phone number or password. Please try again.";
export const INVALID_EMAIL_OR_PHONE_NUMBER = "Invalid email or phone number. Please try again.";