//Font Size
const FONT_SIZE_SMALL = 12;
const FONT_SIZE_MEDIUM = 16;
const FONT_SIZE_LARGE = 20;
const FONT_SIZE_XLARGE = 24;


//

const FONT_WEIGHT_LIGHT = '300';
const FONT_WEIGHT_REGULAR = '400';
const FONT_WEIGHT_MEDIUM = '500';
const FONT_WEIGHT_BOLD = '700';
