// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/enums/PermissionTypes.proto" (package "enums", syntax proto3)
// tslint:disable
/**
 * *
 * PermissionType enumeration
 * Represents different types of permissions
 *
 * @generated from protobuf enum enums.PermissionType
 */
export enum PermissionType {
    /**
     * *
     * Notifications permission type
     * This value represents permission for notifications
     *
     * @generated from protobuf enum value: NOTIFICATIONS = 0;
     */
    NOTIFICATIONS = 0,
    /**
     * *
     * Location permission type
     * This value represents permission for location access
     *
     * @generated from protobuf enum value: LOCATION = 1;
     */
    LOCATION = 1
}
