// Original file: frontend/FrontendService.proto

import type * as grpc from '@grpc/grpc-js'
import type { MethodDefinition } from '@grpc/proto-loader'
import type { GetPhoneVerificationScreenRequest as _Phone_Verification_GetPhoneVerificationScreenRequest, GetPhoneVerificationScreenRequest__Output as _Phone_Verification_GetPhoneVerificationScreenRequest__Output } from '../Phone_Verification/GetPhoneVerificationScreenRequest';
import type { GetPhoneVerificationScreenResponse as _Phone_Verification_GetPhoneVerificationScreenResponse, GetPhoneVerificationScreenResponse__Output as _Phone_Verification_GetPhoneVerificationScreenResponse__Output } from '../Phone_Verification/GetPhoneVerificationScreenResponse';

export interface PhoneVerificationServiceClient extends grpc.Client {
  GetPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  GetPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  GetPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  GetPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  getPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  getPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, metadata: grpc.Metadata, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  getPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, options: grpc.CallOptions, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  getPhoneVerificationScreen(argument: _Phone_Verification_GetPhoneVerificationScreenRequest, callback: grpc.requestCallback<_Phone_Verification_GetPhoneVerificationScreenResponse__Output>): grpc.ClientUnaryCall;
  
}

export interface PhoneVerificationServiceHandlers extends grpc.UntypedServiceImplementation {
  GetPhoneVerificationScreen: grpc.handleUnaryCall<_Phone_Verification_GetPhoneVerificationScreenRequest__Output, _Phone_Verification_GetPhoneVerificationScreenResponse>;
  
}

export interface PhoneVerificationServiceDefinition extends grpc.ServiceDefinition {
  GetPhoneVerificationScreen: MethodDefinition<_Phone_Verification_GetPhoneVerificationScreenRequest, _Phone_Verification_GetPhoneVerificationScreenResponse, _Phone_Verification_GetPhoneVerificationScreenRequest__Output, _Phone_Verification_GetPhoneVerificationScreenResponse__Output>
}
