// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/home/screen_options.proto" (package "home", syntax proto3)
// tslint:disable
import type {BinaryWriteOptions} from '@protobuf-ts/runtime';
import type {IBinaryWriter} from '@protobuf-ts/runtime';
import {UnknownFieldHandler} from '@protobuf-ts/runtime';
import type {BinaryReadOptions} from '@protobuf-ts/runtime';
import type {IBinaryReader} from '@protobuf-ts/runtime';
import type {PartialMessage} from '@protobuf-ts/runtime';
import {reflectionMergePartial} from '@protobuf-ts/runtime';
import {MessageType} from '@protobuf-ts/runtime';
/**
 * @generated from protobuf message home.DummyScreen
 */
export interface DummyScreen {}
// @generated message type with reflection information, may provide speed optimized methods
class DummyScreen$Type extends MessageType<DummyScreen> {
  constructor() {
    super('home.DummyScreen', []);
  }
  create(value?: PartialMessage<DummyScreen>): DummyScreen {
    const message = globalThis.Object.create(this.messagePrototype!);
    if (value !== undefined)
      reflectionMergePartial<DummyScreen>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: DummyScreen,
  ): DummyScreen {
    return target ?? this.create();
  }
  internalBinaryWrite(
    message: DummyScreen,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message home.DummyScreen
 */
export const DummyScreen = new DummyScreen$Type();
