// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/frontend/frontend_service.proto" (package "frontend", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FrontendService } from "./frontend_service";
import type { GetCurrentOnboardingStageResponse } from "../onboarding/rpc_responses";
import type { EmptyRequest } from "../generic/generic_messages";
import type { TriggerLivenessCheckResponse } from "../onboarding/rpc_responses";
import type { TriggerLivenessCheckRequest } from "../onboarding/rpc_requests";
import type { TriggerPanVerificationResponse } from "../onboarding/rpc_responses";
import type { TriggerPanVerificationRequest } from "../onboarding/rpc_requests";
import type { TriggerEmailVerificationResponse } from "../onboarding/rpc_responses";
import type { TriggerEmailVerificationRequest } from "../onboarding/rpc_requests";
import type { TriggerPhoneOTPVerificationResponse } from "../onboarding/rpc_responses";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TriggerPhoneVerificationResponse } from "../onboarding/rpc_responses";
import type { TriggerPhoneOTPVerificationRequest } from "../onboarding/rpc_requests";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Define the service
 *
 * @generated from protobuf service frontend.FrontendService
 */
export interface IFrontendServiceClient {
    /**
     * @generated from protobuf rpc: TriggerPhoneVerification(onboarding.TriggerPhoneOTPVerificationRequest) returns (onboarding.TriggerPhoneVerificationResponse);
     */
    triggerPhoneVerification(input: TriggerPhoneOTPVerificationRequest, options?: RpcOptions): UnaryCall<TriggerPhoneOTPVerificationRequest, TriggerPhoneVerificationResponse>;
    /**
     * @generated from protobuf rpc: TriggerPhoneOTPVerification(onboarding.TriggerPhoneOTPVerificationRequest) returns (onboarding.TriggerPhoneOTPVerificationResponse);
     */
    triggerPhoneOTPVerification(input: TriggerPhoneOTPVerificationRequest, options?: RpcOptions): UnaryCall<TriggerPhoneOTPVerificationRequest, TriggerPhoneOTPVerificationResponse>;
    /**
     * @generated from protobuf rpc: TriggerEmailVerification(onboarding.TriggerEmailVerificationRequest) returns (onboarding.TriggerEmailVerificationResponse);
     */
    triggerEmailVerification(input: TriggerEmailVerificationRequest, options?: RpcOptions): UnaryCall<TriggerEmailVerificationRequest, TriggerEmailVerificationResponse>;
    /**
     * @generated from protobuf rpc: TriggerPanVerification(onboarding.TriggerPanVerificationRequest) returns (onboarding.TriggerPanVerificationResponse);
     */
    triggerPanVerification(input: TriggerPanVerificationRequest, options?: RpcOptions): UnaryCall<TriggerPanVerificationRequest, TriggerPanVerificationResponse>;
    /**
     * @generated from protobuf rpc: TriggerLivenessCheck(onboarding.TriggerLivenessCheckRequest) returns (onboarding.TriggerLivenessCheckResponse);
     */
    triggerLivenessCheck(input: TriggerLivenessCheckRequest, options?: RpcOptions): UnaryCall<TriggerLivenessCheckRequest, TriggerLivenessCheckResponse>;
    /**
     * @generated from protobuf rpc: GetCurrentOnboardingStage(generic.EmptyRequest) returns (onboarding.GetCurrentOnboardingStageResponse);
     */
    getCurrentOnboardingStage(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, GetCurrentOnboardingStageResponse>;
}
/**
 * Define the service
 *
 * @generated from protobuf service frontend.FrontendService
 */
export class FrontendServiceClient implements IFrontendServiceClient, ServiceInfo {
    typeName = FrontendService.typeName;
    methods = FrontendService.methods;
    options = FrontendService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: TriggerPhoneVerification(onboarding.TriggerPhoneOTPVerificationRequest) returns (onboarding.TriggerPhoneVerificationResponse);
     */
    triggerPhoneVerification(input: TriggerPhoneOTPVerificationRequest, options?: RpcOptions): UnaryCall<TriggerPhoneOTPVerificationRequest, TriggerPhoneVerificationResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerPhoneOTPVerificationRequest, TriggerPhoneVerificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TriggerPhoneOTPVerification(onboarding.TriggerPhoneOTPVerificationRequest) returns (onboarding.TriggerPhoneOTPVerificationResponse);
     */
    triggerPhoneOTPVerification(input: TriggerPhoneOTPVerificationRequest, options?: RpcOptions): UnaryCall<TriggerPhoneOTPVerificationRequest, TriggerPhoneOTPVerificationResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerPhoneOTPVerificationRequest, TriggerPhoneOTPVerificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TriggerEmailVerification(onboarding.TriggerEmailVerificationRequest) returns (onboarding.TriggerEmailVerificationResponse);
     */
    triggerEmailVerification(input: TriggerEmailVerificationRequest, options?: RpcOptions): UnaryCall<TriggerEmailVerificationRequest, TriggerEmailVerificationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerEmailVerificationRequest, TriggerEmailVerificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TriggerPanVerification(onboarding.TriggerPanVerificationRequest) returns (onboarding.TriggerPanVerificationResponse);
     */
    triggerPanVerification(input: TriggerPanVerificationRequest, options?: RpcOptions): UnaryCall<TriggerPanVerificationRequest, TriggerPanVerificationResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerPanVerificationRequest, TriggerPanVerificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TriggerLivenessCheck(onboarding.TriggerLivenessCheckRequest) returns (onboarding.TriggerLivenessCheckResponse);
     */
    triggerLivenessCheck(input: TriggerLivenessCheckRequest, options?: RpcOptions): UnaryCall<TriggerLivenessCheckRequest, TriggerLivenessCheckResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerLivenessCheckRequest, TriggerLivenessCheckResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCurrentOnboardingStage(generic.EmptyRequest) returns (onboarding.GetCurrentOnboardingStageResponse);
     */
    getCurrentOnboardingStage(input: EmptyRequest, options?: RpcOptions): UnaryCall<EmptyRequest, GetCurrentOnboardingStageResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<EmptyRequest, GetCurrentOnboardingStageResponse>("unary", this._transport, method, opt, input);
    }
}
