// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/frontend/FrontendService.proto" (package "frontend", syntax proto3)
// tslint:disable
import { GetCurrentOnboardingStageResponse } from "../onboarding/rpc";
import { GetOtherConsentsScreenResponse } from "../onboarding/rpc";
import { GetBiometricConsentScreenResponse } from "../onboarding/rpc";
import { TriggerLivenessCheckResponse } from "../onboarding/rpc";
import { TriggerLivenessCheckRequest } from "../onboarding/rpc";
import { GetLivenessCheckScreenResponse } from "../onboarding/rpc";
import { TriggerPanVerificationResponse } from "../onboarding/rpc";
import { TriggerPanVerificationRequest } from "../onboarding/rpc";
import { GetPanVerificationScreenResponse } from "../onboarding/rpc";
import { TriggerEmailVerificationResponse } from "../onboarding/rpc";
import { TriggerEmailVerificationRequest } from "../onboarding/rpc";
import { GetEmailVerificationScreenResponse } from "../onboarding/rpc";
import { TriggerPhoneOTPVerificationResponse } from "../onboarding/rpc";
import { GetPhoneOTPVerificationScreenResponse } from "../onboarding/rpc";
import { TriggerPhoneVerificationResponse } from "../onboarding/rpc";
import { TriggerPhoneOTPVerificationRequest } from "../onboarding/rpc";
import { GetPhoneVerificationScreenResponse } from "../onboarding/rpc";
import { EmptyRequest } from "../generic/GenericMessages";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service frontend.FrontendService
 */
export const FrontendService = new ServiceType("frontend.FrontendService", [
    { name: "GetPhoneVerificationScreen", options: {}, I: EmptyRequest, O: GetPhoneVerificationScreenResponse },
    { name: "TriggerPhoneVerification", options: {}, I: TriggerPhoneOTPVerificationRequest, O: TriggerPhoneVerificationResponse },
    { name: "GetPhoneOTPVerificationScreen", options: {}, I: EmptyRequest, O: GetPhoneOTPVerificationScreenResponse },
    { name: "TriggerPhoneOTPVerification", options: {}, I: TriggerPhoneOTPVerificationRequest, O: TriggerPhoneOTPVerificationResponse },
    { name: "GetEmailVerificationScreen", options: {}, I: EmptyRequest, O: GetEmailVerificationScreenResponse },
    { name: "TriggerEmailVerification", options: {}, I: TriggerEmailVerificationRequest, O: TriggerEmailVerificationResponse },
    { name: "GetPanVerificationScreen", options: {}, I: EmptyRequest, O: GetPanVerificationScreenResponse },
    { name: "TriggerPanVerification", options: {}, I: TriggerPanVerificationRequest, O: TriggerPanVerificationResponse },
    { name: "GetLivenessCheckScreen", options: {}, I: EmptyRequest, O: GetLivenessCheckScreenResponse },
    { name: "TriggerLivenessCheck", options: {}, I: TriggerLivenessCheckRequest, O: TriggerLivenessCheckResponse },
    { name: "GetBiometricConsentScreen", options: {}, I: EmptyRequest, O: GetBiometricConsentScreenResponse },
    { name: "GetOtherConsentsScreen", options: {}, I: EmptyRequest, O: GetOtherConsentsScreenResponse },
    { name: "GetCurrentOnboardingStage", options: {}, I: EmptyRequest, O: GetCurrentOnboardingStageResponse }
]);
