// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/frontend/frontend_service.proto" (package "frontend", syntax proto3)
// tslint:disable
import { GetCurrentOnboardingStageResponse } from "../onboarding/rpc_responses";
import { EmptyRequest } from "../generic/generic_messages";
import { TriggerLivenessCheckResponse } from "../onboarding/rpc_responses";
import { TriggerLivenessCheckRequest } from "../onboarding/rpc_requests";
import { TriggerPanVerificationResponse } from "../onboarding/rpc_responses";
import { TriggerPanVerificationRequest } from "../onboarding/rpc_requests";
import { TriggerEmailVerificationResponse } from "../onboarding/rpc_responses";
import { TriggerEmailVerificationRequest } from "../onboarding/rpc_requests";
import { TriggerPhoneOTPVerificationResponse } from "../onboarding/rpc_responses";
import { TriggerPhoneVerificationResponse } from "../onboarding/rpc_responses";
import { TriggerPhoneOTPVerificationRequest } from "../onboarding/rpc_requests";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service frontend.FrontendService
 */
export const FrontendService = new ServiceType("frontend.FrontendService", [
    { name: "TriggerPhoneVerification", options: {}, I: TriggerPhoneOTPVerificationRequest, O: TriggerPhoneVerificationResponse },
    { name: "TriggerPhoneOTPVerification", options: {}, I: TriggerPhoneOTPVerificationRequest, O: TriggerPhoneOTPVerificationResponse },
    { name: "TriggerEmailVerification", options: {}, I: TriggerEmailVerificationRequest, O: TriggerEmailVerificationResponse },
    { name: "TriggerPanVerification", options: {}, I: TriggerPanVerificationRequest, O: TriggerPanVerificationResponse },
    { name: "TriggerLivenessCheck", options: {}, I: TriggerLivenessCheckRequest, O: TriggerLivenessCheckResponse },
    { name: "GetCurrentOnboardingStage", options: {}, I: EmptyRequest, O: GetCurrentOnboardingStageResponse }
]);
