// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v5.27.1
// source: protos-frontend/frontend/FrontendService.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Button } from "../UI/Button";
import {
  LivenessCheckStatus,
  livenessCheckStatusFromJSON,
  livenessCheckStatusToJSON,
  VerificationResponseType,
  verificationResponseTypeFromJSON,
  verificationResponseTypeToJSON,
} from "../enums/ResponseType";
import { EmptyRequest } from "./generic/GenericMessages";

export const protobufPackage = "frontend";

export interface GetPhoneVerificationScreenResponse {
  title: string;
  subTitle: string;
  phoneNumberHeading: string;
  inputNumber: string;
  phoneNumberBreifing: string;
  img1Url: string;
  primaryButton: Button | undefined;
}

export interface TriggerPhoneVerificationResponse {
  responseType: VerificationResponseType;
}

export interface GetPhoneOTPVerificationScreenResponse {
  title: string;
  description: string;
  waitText: string;
  timerInSeconds: number;
  resendOtpText: string;
  primaryButton: Button | undefined;
}

export interface TriggerPhoneOTPVerificationRequest {
  otp: string;
}

export interface TriggerPhoneOTPVerificationResponse {
  responseType: VerificationResponseType;
}

export interface GetEmailVerificationScreenResponse {
  title: string;
  subTitle: string;
  primaryButton: Button | undefined;
  imgUrl: string;
}

export interface TriggerEmailVerificationRequest {
  emailId: string;
  userName: string;
}

export interface TriggerEmailVerificationResponse {
  responseType: VerificationResponseType;
}

export interface GetPanVerificationScreenResponse {
  imageUrl: string;
  title: string;
  description: string;
  panNumber: string;
  dateOfBirth: Date | undefined;
  detailsStoragePermissionText: string;
  infoUsagePermissionText: string;
  nextButton: Button | undefined;
  noPanText: string;
}

export interface TriggerPanVerificationRequest {
  panNumber: string;
  dateOfBirth: Date | undefined;
}

export interface TriggerPanVerificationResponse {
  responseType: VerificationResponseType;
  otp: string;
}

export interface GetLivenessCheckScreenResponse {
  otpToShow: string;
  nextButton: Button | undefined;
}

export interface TriggerLivenessCheckRequest {
  otpSpoken: string;
}

export interface TriggerLivenessCheckResponse {
  livenessCheckStatus: LivenessCheckStatus;
}

function createBaseGetPhoneVerificationScreenResponse(): GetPhoneVerificationScreenResponse {
  return {
    title: "",
    subTitle: "",
    phoneNumberHeading: "",
    inputNumber: "",
    phoneNumberBreifing: "",
    img1Url: "",
    primaryButton: undefined,
  };
}

export const GetPhoneVerificationScreenResponse = {
  encode(message: GetPhoneVerificationScreenResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.subTitle !== "") {
      writer.uint32(18).string(message.subTitle);
    }
    if (message.phoneNumberHeading !== "") {
      writer.uint32(26).string(message.phoneNumberHeading);
    }
    if (message.inputNumber !== "") {
      writer.uint32(34).string(message.inputNumber);
    }
    if (message.phoneNumberBreifing !== "") {
      writer.uint32(42).string(message.phoneNumberBreifing);
    }
    if (message.img1Url !== "") {
      writer.uint32(50).string(message.img1Url);
    }
    if (message.primaryButton !== undefined) {
      Button.encode(message.primaryButton, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPhoneVerificationScreenResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhoneVerificationScreenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.subTitle = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.phoneNumberHeading = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.inputNumber = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.phoneNumberBreifing = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.img1Url = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.primaryButton = Button.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPhoneVerificationScreenResponse {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      subTitle: isSet(object.subTitle) ? globalThis.String(object.subTitle) : "",
      phoneNumberHeading: isSet(object.phoneNumberHeading) ? globalThis.String(object.phoneNumberHeading) : "",
      inputNumber: isSet(object.inputNumber) ? globalThis.String(object.inputNumber) : "",
      phoneNumberBreifing: isSet(object.phoneNumberBreifing) ? globalThis.String(object.phoneNumberBreifing) : "",
      img1Url: isSet(object.img1Url) ? globalThis.String(object.img1Url) : "",
      primaryButton: isSet(object.primaryButton) ? Button.fromJSON(object.primaryButton) : undefined,
    };
  },

  toJSON(message: GetPhoneVerificationScreenResponse): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.subTitle !== "") {
      obj.subTitle = message.subTitle;
    }
    if (message.phoneNumberHeading !== "") {
      obj.phoneNumberHeading = message.phoneNumberHeading;
    }
    if (message.inputNumber !== "") {
      obj.inputNumber = message.inputNumber;
    }
    if (message.phoneNumberBreifing !== "") {
      obj.phoneNumberBreifing = message.phoneNumberBreifing;
    }
    if (message.img1Url !== "") {
      obj.img1Url = message.img1Url;
    }
    if (message.primaryButton !== undefined) {
      obj.primaryButton = Button.toJSON(message.primaryButton);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPhoneVerificationScreenResponse>, I>>(
    base?: I,
  ): GetPhoneVerificationScreenResponse {
    return GetPhoneVerificationScreenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPhoneVerificationScreenResponse>, I>>(
    object: I,
  ): GetPhoneVerificationScreenResponse {
    const message = createBaseGetPhoneVerificationScreenResponse();
    message.title = object.title ?? "";
    message.subTitle = object.subTitle ?? "";
    message.phoneNumberHeading = object.phoneNumberHeading ?? "";
    message.inputNumber = object.inputNumber ?? "";
    message.phoneNumberBreifing = object.phoneNumberBreifing ?? "";
    message.img1Url = object.img1Url ?? "";
    message.primaryButton = (object.primaryButton !== undefined && object.primaryButton !== null)
      ? Button.fromPartial(object.primaryButton)
      : undefined;
    return message;
  },
};

function createBaseTriggerPhoneVerificationResponse(): TriggerPhoneVerificationResponse {
  return { responseType: 0 };
}

export const TriggerPhoneVerificationResponse = {
  encode(message: TriggerPhoneVerificationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.responseType !== 0) {
      writer.uint32(8).int32(message.responseType);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerPhoneVerificationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerPhoneVerificationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerPhoneVerificationResponse {
    return { responseType: isSet(object.responseType) ? verificationResponseTypeFromJSON(object.responseType) : 0 };
  },

  toJSON(message: TriggerPhoneVerificationResponse): unknown {
    const obj: any = {};
    if (message.responseType !== 0) {
      obj.responseType = verificationResponseTypeToJSON(message.responseType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerPhoneVerificationResponse>, I>>(
    base?: I,
  ): TriggerPhoneVerificationResponse {
    return TriggerPhoneVerificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerPhoneVerificationResponse>, I>>(
    object: I,
  ): TriggerPhoneVerificationResponse {
    const message = createBaseTriggerPhoneVerificationResponse();
    message.responseType = object.responseType ?? 0;
    return message;
  },
};

function createBaseGetPhoneOTPVerificationScreenResponse(): GetPhoneOTPVerificationScreenResponse {
  return { title: "", description: "", waitText: "", timerInSeconds: 0, resendOtpText: "", primaryButton: undefined };
}

export const GetPhoneOTPVerificationScreenResponse = {
  encode(message: GetPhoneOTPVerificationScreenResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.waitText !== "") {
      writer.uint32(26).string(message.waitText);
    }
    if (message.timerInSeconds !== 0) {
      writer.uint32(32).int32(message.timerInSeconds);
    }
    if (message.resendOtpText !== "") {
      writer.uint32(42).string(message.resendOtpText);
    }
    if (message.primaryButton !== undefined) {
      Button.encode(message.primaryButton, writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPhoneOTPVerificationScreenResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPhoneOTPVerificationScreenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.waitText = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.timerInSeconds = reader.int32();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.resendOtpText = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.primaryButton = Button.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPhoneOTPVerificationScreenResponse {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      waitText: isSet(object.waitText) ? globalThis.String(object.waitText) : "",
      timerInSeconds: isSet(object.timerInSeconds) ? globalThis.Number(object.timerInSeconds) : 0,
      resendOtpText: isSet(object.resendOtpText) ? globalThis.String(object.resendOtpText) : "",
      primaryButton: isSet(object.primaryButton) ? Button.fromJSON(object.primaryButton) : undefined,
    };
  },

  toJSON(message: GetPhoneOTPVerificationScreenResponse): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.waitText !== "") {
      obj.waitText = message.waitText;
    }
    if (message.timerInSeconds !== 0) {
      obj.timerInSeconds = Math.round(message.timerInSeconds);
    }
    if (message.resendOtpText !== "") {
      obj.resendOtpText = message.resendOtpText;
    }
    if (message.primaryButton !== undefined) {
      obj.primaryButton = Button.toJSON(message.primaryButton);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPhoneOTPVerificationScreenResponse>, I>>(
    base?: I,
  ): GetPhoneOTPVerificationScreenResponse {
    return GetPhoneOTPVerificationScreenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPhoneOTPVerificationScreenResponse>, I>>(
    object: I,
  ): GetPhoneOTPVerificationScreenResponse {
    const message = createBaseGetPhoneOTPVerificationScreenResponse();
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.waitText = object.waitText ?? "";
    message.timerInSeconds = object.timerInSeconds ?? 0;
    message.resendOtpText = object.resendOtpText ?? "";
    message.primaryButton = (object.primaryButton !== undefined && object.primaryButton !== null)
      ? Button.fromPartial(object.primaryButton)
      : undefined;
    return message;
  },
};

function createBaseTriggerPhoneOTPVerificationRequest(): TriggerPhoneOTPVerificationRequest {
  return { otp: "" };
}

export const TriggerPhoneOTPVerificationRequest = {
  encode(message: TriggerPhoneOTPVerificationRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.otp !== "") {
      writer.uint32(10).string(message.otp);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerPhoneOTPVerificationRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerPhoneOTPVerificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.otp = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerPhoneOTPVerificationRequest {
    return { otp: isSet(object.otp) ? globalThis.String(object.otp) : "" };
  },

  toJSON(message: TriggerPhoneOTPVerificationRequest): unknown {
    const obj: any = {};
    if (message.otp !== "") {
      obj.otp = message.otp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerPhoneOTPVerificationRequest>, I>>(
    base?: I,
  ): TriggerPhoneOTPVerificationRequest {
    return TriggerPhoneOTPVerificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerPhoneOTPVerificationRequest>, I>>(
    object: I,
  ): TriggerPhoneOTPVerificationRequest {
    const message = createBaseTriggerPhoneOTPVerificationRequest();
    message.otp = object.otp ?? "";
    return message;
  },
};

function createBaseTriggerPhoneOTPVerificationResponse(): TriggerPhoneOTPVerificationResponse {
  return { responseType: 0 };
}

export const TriggerPhoneOTPVerificationResponse = {
  encode(message: TriggerPhoneOTPVerificationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.responseType !== 0) {
      writer.uint32(8).int32(message.responseType);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerPhoneOTPVerificationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerPhoneOTPVerificationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerPhoneOTPVerificationResponse {
    return { responseType: isSet(object.responseType) ? verificationResponseTypeFromJSON(object.responseType) : 0 };
  },

  toJSON(message: TriggerPhoneOTPVerificationResponse): unknown {
    const obj: any = {};
    if (message.responseType !== 0) {
      obj.responseType = verificationResponseTypeToJSON(message.responseType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerPhoneOTPVerificationResponse>, I>>(
    base?: I,
  ): TriggerPhoneOTPVerificationResponse {
    return TriggerPhoneOTPVerificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerPhoneOTPVerificationResponse>, I>>(
    object: I,
  ): TriggerPhoneOTPVerificationResponse {
    const message = createBaseTriggerPhoneOTPVerificationResponse();
    message.responseType = object.responseType ?? 0;
    return message;
  },
};

function createBaseGetEmailVerificationScreenResponse(): GetEmailVerificationScreenResponse {
  return { title: "", subTitle: "", primaryButton: undefined, imgUrl: "" };
}

export const GetEmailVerificationScreenResponse = {
  encode(message: GetEmailVerificationScreenResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.subTitle !== "") {
      writer.uint32(18).string(message.subTitle);
    }
    if (message.primaryButton !== undefined) {
      Button.encode(message.primaryButton, writer.uint32(26).fork()).ldelim();
    }
    if (message.imgUrl !== "") {
      writer.uint32(34).string(message.imgUrl);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetEmailVerificationScreenResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetEmailVerificationScreenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.subTitle = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.primaryButton = Button.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.imgUrl = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetEmailVerificationScreenResponse {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      subTitle: isSet(object.subTitle) ? globalThis.String(object.subTitle) : "",
      primaryButton: isSet(object.primaryButton) ? Button.fromJSON(object.primaryButton) : undefined,
      imgUrl: isSet(object.imgUrl) ? globalThis.String(object.imgUrl) : "",
    };
  },

  toJSON(message: GetEmailVerificationScreenResponse): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.subTitle !== "") {
      obj.subTitle = message.subTitle;
    }
    if (message.primaryButton !== undefined) {
      obj.primaryButton = Button.toJSON(message.primaryButton);
    }
    if (message.imgUrl !== "") {
      obj.imgUrl = message.imgUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetEmailVerificationScreenResponse>, I>>(
    base?: I,
  ): GetEmailVerificationScreenResponse {
    return GetEmailVerificationScreenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetEmailVerificationScreenResponse>, I>>(
    object: I,
  ): GetEmailVerificationScreenResponse {
    const message = createBaseGetEmailVerificationScreenResponse();
    message.title = object.title ?? "";
    message.subTitle = object.subTitle ?? "";
    message.primaryButton = (object.primaryButton !== undefined && object.primaryButton !== null)
      ? Button.fromPartial(object.primaryButton)
      : undefined;
    message.imgUrl = object.imgUrl ?? "";
    return message;
  },
};

function createBaseTriggerEmailVerificationRequest(): TriggerEmailVerificationRequest {
  return { emailId: "", userName: "" };
}

export const TriggerEmailVerificationRequest = {
  encode(message: TriggerEmailVerificationRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.emailId !== "") {
      writer.uint32(10).string(message.emailId);
    }
    if (message.userName !== "") {
      writer.uint32(18).string(message.userName);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerEmailVerificationRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerEmailVerificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.emailId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.userName = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerEmailVerificationRequest {
    return {
      emailId: isSet(object.emailId) ? globalThis.String(object.emailId) : "",
      userName: isSet(object.userName) ? globalThis.String(object.userName) : "",
    };
  },

  toJSON(message: TriggerEmailVerificationRequest): unknown {
    const obj: any = {};
    if (message.emailId !== "") {
      obj.emailId = message.emailId;
    }
    if (message.userName !== "") {
      obj.userName = message.userName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerEmailVerificationRequest>, I>>(base?: I): TriggerEmailVerificationRequest {
    return TriggerEmailVerificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerEmailVerificationRequest>, I>>(
    object: I,
  ): TriggerEmailVerificationRequest {
    const message = createBaseTriggerEmailVerificationRequest();
    message.emailId = object.emailId ?? "";
    message.userName = object.userName ?? "";
    return message;
  },
};

function createBaseTriggerEmailVerificationResponse(): TriggerEmailVerificationResponse {
  return { responseType: 0 };
}

export const TriggerEmailVerificationResponse = {
  encode(message: TriggerEmailVerificationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.responseType !== 0) {
      writer.uint32(8).int32(message.responseType);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerEmailVerificationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerEmailVerificationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerEmailVerificationResponse {
    return { responseType: isSet(object.responseType) ? verificationResponseTypeFromJSON(object.responseType) : 0 };
  },

  toJSON(message: TriggerEmailVerificationResponse): unknown {
    const obj: any = {};
    if (message.responseType !== 0) {
      obj.responseType = verificationResponseTypeToJSON(message.responseType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerEmailVerificationResponse>, I>>(
    base?: I,
  ): TriggerEmailVerificationResponse {
    return TriggerEmailVerificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerEmailVerificationResponse>, I>>(
    object: I,
  ): TriggerEmailVerificationResponse {
    const message = createBaseTriggerEmailVerificationResponse();
    message.responseType = object.responseType ?? 0;
    return message;
  },
};

function createBaseGetPanVerificationScreenResponse(): GetPanVerificationScreenResponse {
  return {
    imageUrl: "",
    title: "",
    description: "",
    panNumber: "",
    dateOfBirth: undefined,
    detailsStoragePermissionText: "",
    infoUsagePermissionText: "",
    nextButton: undefined,
    noPanText: "",
  };
}

export const GetPanVerificationScreenResponse = {
  encode(message: GetPanVerificationScreenResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.imageUrl !== "") {
      writer.uint32(10).string(message.imageUrl);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.panNumber !== "") {
      writer.uint32(34).string(message.panNumber);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(42).fork()).ldelim();
    }
    if (message.detailsStoragePermissionText !== "") {
      writer.uint32(50).string(message.detailsStoragePermissionText);
    }
    if (message.infoUsagePermissionText !== "") {
      writer.uint32(58).string(message.infoUsagePermissionText);
    }
    if (message.nextButton !== undefined) {
      Button.encode(message.nextButton, writer.uint32(66).fork()).ldelim();
    }
    if (message.noPanText !== "") {
      writer.uint32(74).string(message.noPanText);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetPanVerificationScreenResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPanVerificationScreenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.imageUrl = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.panNumber = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.detailsStoragePermissionText = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.infoUsagePermissionText = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.nextButton = Button.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.noPanText = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPanVerificationScreenResponse {
    return {
      imageUrl: isSet(object.imageUrl) ? globalThis.String(object.imageUrl) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      panNumber: isSet(object.panNumber) ? globalThis.String(object.panNumber) : "",
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      detailsStoragePermissionText: isSet(object.detailsStoragePermissionText)
        ? globalThis.String(object.detailsStoragePermissionText)
        : "",
      infoUsagePermissionText: isSet(object.infoUsagePermissionText)
        ? globalThis.String(object.infoUsagePermissionText)
        : "",
      nextButton: isSet(object.nextButton) ? Button.fromJSON(object.nextButton) : undefined,
      noPanText: isSet(object.noPanText) ? globalThis.String(object.noPanText) : "",
    };
  },

  toJSON(message: GetPanVerificationScreenResponse): unknown {
    const obj: any = {};
    if (message.imageUrl !== "") {
      obj.imageUrl = message.imageUrl;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.panNumber !== "") {
      obj.panNumber = message.panNumber;
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.detailsStoragePermissionText !== "") {
      obj.detailsStoragePermissionText = message.detailsStoragePermissionText;
    }
    if (message.infoUsagePermissionText !== "") {
      obj.infoUsagePermissionText = message.infoUsagePermissionText;
    }
    if (message.nextButton !== undefined) {
      obj.nextButton = Button.toJSON(message.nextButton);
    }
    if (message.noPanText !== "") {
      obj.noPanText = message.noPanText;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPanVerificationScreenResponse>, I>>(
    base?: I,
  ): GetPanVerificationScreenResponse {
    return GetPanVerificationScreenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPanVerificationScreenResponse>, I>>(
    object: I,
  ): GetPanVerificationScreenResponse {
    const message = createBaseGetPanVerificationScreenResponse();
    message.imageUrl = object.imageUrl ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.panNumber = object.panNumber ?? "";
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.detailsStoragePermissionText = object.detailsStoragePermissionText ?? "";
    message.infoUsagePermissionText = object.infoUsagePermissionText ?? "";
    message.nextButton = (object.nextButton !== undefined && object.nextButton !== null)
      ? Button.fromPartial(object.nextButton)
      : undefined;
    message.noPanText = object.noPanText ?? "";
    return message;
  },
};

function createBaseTriggerPanVerificationRequest(): TriggerPanVerificationRequest {
  return { panNumber: "", dateOfBirth: undefined };
}

export const TriggerPanVerificationRequest = {
  encode(message: TriggerPanVerificationRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.panNumber !== "") {
      writer.uint32(10).string(message.panNumber);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerPanVerificationRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerPanVerificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.panNumber = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerPanVerificationRequest {
    return {
      panNumber: isSet(object.panNumber) ? globalThis.String(object.panNumber) : "",
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
    };
  },

  toJSON(message: TriggerPanVerificationRequest): unknown {
    const obj: any = {};
    if (message.panNumber !== "") {
      obj.panNumber = message.panNumber;
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerPanVerificationRequest>, I>>(base?: I): TriggerPanVerificationRequest {
    return TriggerPanVerificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerPanVerificationRequest>, I>>(
    object: I,
  ): TriggerPanVerificationRequest {
    const message = createBaseTriggerPanVerificationRequest();
    message.panNumber = object.panNumber ?? "";
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    return message;
  },
};

function createBaseTriggerPanVerificationResponse(): TriggerPanVerificationResponse {
  return { responseType: 0, otp: "" };
}

export const TriggerPanVerificationResponse = {
  encode(message: TriggerPanVerificationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.responseType !== 0) {
      writer.uint32(8).int32(message.responseType);
    }
    if (message.otp !== "") {
      writer.uint32(18).string(message.otp);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerPanVerificationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerPanVerificationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.responseType = reader.int32() as any;
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.otp = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerPanVerificationResponse {
    return {
      responseType: isSet(object.responseType) ? verificationResponseTypeFromJSON(object.responseType) : 0,
      otp: isSet(object.otp) ? globalThis.String(object.otp) : "",
    };
  },

  toJSON(message: TriggerPanVerificationResponse): unknown {
    const obj: any = {};
    if (message.responseType !== 0) {
      obj.responseType = verificationResponseTypeToJSON(message.responseType);
    }
    if (message.otp !== "") {
      obj.otp = message.otp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerPanVerificationResponse>, I>>(base?: I): TriggerPanVerificationResponse {
    return TriggerPanVerificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerPanVerificationResponse>, I>>(
    object: I,
  ): TriggerPanVerificationResponse {
    const message = createBaseTriggerPanVerificationResponse();
    message.responseType = object.responseType ?? 0;
    message.otp = object.otp ?? "";
    return message;
  },
};

function createBaseGetLivenessCheckScreenResponse(): GetLivenessCheckScreenResponse {
  return { otpToShow: "", nextButton: undefined };
}

export const GetLivenessCheckScreenResponse = {
  encode(message: GetLivenessCheckScreenResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.otpToShow !== "") {
      writer.uint32(10).string(message.otpToShow);
    }
    if (message.nextButton !== undefined) {
      Button.encode(message.nextButton, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetLivenessCheckScreenResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLivenessCheckScreenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.otpToShow = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.nextButton = Button.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLivenessCheckScreenResponse {
    return {
      otpToShow: isSet(object.otpToShow) ? globalThis.String(object.otpToShow) : "",
      nextButton: isSet(object.nextButton) ? Button.fromJSON(object.nextButton) : undefined,
    };
  },

  toJSON(message: GetLivenessCheckScreenResponse): unknown {
    const obj: any = {};
    if (message.otpToShow !== "") {
      obj.otpToShow = message.otpToShow;
    }
    if (message.nextButton !== undefined) {
      obj.nextButton = Button.toJSON(message.nextButton);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLivenessCheckScreenResponse>, I>>(base?: I): GetLivenessCheckScreenResponse {
    return GetLivenessCheckScreenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLivenessCheckScreenResponse>, I>>(
    object: I,
  ): GetLivenessCheckScreenResponse {
    const message = createBaseGetLivenessCheckScreenResponse();
    message.otpToShow = object.otpToShow ?? "";
    message.nextButton = (object.nextButton !== undefined && object.nextButton !== null)
      ? Button.fromPartial(object.nextButton)
      : undefined;
    return message;
  },
};

function createBaseTriggerLivenessCheckRequest(): TriggerLivenessCheckRequest {
  return { otpSpoken: "" };
}

export const TriggerLivenessCheckRequest = {
  encode(message: TriggerLivenessCheckRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.otpSpoken !== "") {
      writer.uint32(10).string(message.otpSpoken);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerLivenessCheckRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerLivenessCheckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.otpSpoken = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerLivenessCheckRequest {
    return { otpSpoken: isSet(object.otpSpoken) ? globalThis.String(object.otpSpoken) : "" };
  },

  toJSON(message: TriggerLivenessCheckRequest): unknown {
    const obj: any = {};
    if (message.otpSpoken !== "") {
      obj.otpSpoken = message.otpSpoken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerLivenessCheckRequest>, I>>(base?: I): TriggerLivenessCheckRequest {
    return TriggerLivenessCheckRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerLivenessCheckRequest>, I>>(object: I): TriggerLivenessCheckRequest {
    const message = createBaseTriggerLivenessCheckRequest();
    message.otpSpoken = object.otpSpoken ?? "";
    return message;
  },
};

function createBaseTriggerLivenessCheckResponse(): TriggerLivenessCheckResponse {
  return { livenessCheckStatus: 0 };
}

export const TriggerLivenessCheckResponse = {
  encode(message: TriggerLivenessCheckResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.livenessCheckStatus !== 0) {
      writer.uint32(8).int32(message.livenessCheckStatus);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TriggerLivenessCheckResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerLivenessCheckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.livenessCheckStatus = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TriggerLivenessCheckResponse {
    return {
      livenessCheckStatus: isSet(object.livenessCheckStatus)
        ? livenessCheckStatusFromJSON(object.livenessCheckStatus)
        : 0,
    };
  },

  toJSON(message: TriggerLivenessCheckResponse): unknown {
    const obj: any = {};
    if (message.livenessCheckStatus !== 0) {
      obj.livenessCheckStatus = livenessCheckStatusToJSON(message.livenessCheckStatus);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TriggerLivenessCheckResponse>, I>>(base?: I): TriggerLivenessCheckResponse {
    return TriggerLivenessCheckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TriggerLivenessCheckResponse>, I>>(object: I): TriggerLivenessCheckResponse {
    const message = createBaseTriggerLivenessCheckResponse();
    message.livenessCheckStatus = object.livenessCheckStatus ?? 0;
    return message;
  },
};

/** Define the service */
export interface FrontendService {
  /** RPC to get the phone verification */
  GetPhoneVerificationScreen(request: EmptyRequest): Promise<GetPhoneVerificationScreenResponse>;
  TriggerPhoneVerification(request: TriggerPhoneOTPVerificationRequest): Promise<TriggerPhoneVerificationResponse>;
  GetPhoneOTPVerificationScreen(request: EmptyRequest): Promise<GetPhoneOTPVerificationScreenResponse>;
  TriggerPhoneOTPVerification(
    request: TriggerPhoneOTPVerificationRequest,
  ): Promise<TriggerPhoneOTPVerificationResponse>;
  GetEmailVerificationScreen(request: EmptyRequest): Promise<GetEmailVerificationScreenResponse>;
  TriggerEmailVerification(request: TriggerEmailVerificationRequest): Promise<TriggerEmailVerificationResponse>;
  GetPanVerificationScreen(request: EmptyRequest): Promise<GetPanVerificationScreenResponse>;
  TriggerPanVerification(request: TriggerPanVerificationRequest): Promise<TriggerPanVerificationResponse>;
  GetLivenessCheckScreen(request: EmptyRequest): Promise<GetLivenessCheckScreenResponse>;
  TriggerLivenessCheck(request: TriggerLivenessCheckRequest): Promise<TriggerLivenessCheckResponse>;
}

export const FrontendServiceServiceName = "frontend.FrontendService";
export class FrontendServiceClientImpl implements FrontendService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || FrontendServiceServiceName;
    this.rpc = rpc;
    this.GetPhoneVerificationScreen = this.GetPhoneVerificationScreen.bind(this);
    this.TriggerPhoneVerification = this.TriggerPhoneVerification.bind(this);
    this.GetPhoneOTPVerificationScreen = this.GetPhoneOTPVerificationScreen.bind(this);
    this.TriggerPhoneOTPVerification = this.TriggerPhoneOTPVerification.bind(this);
    this.GetEmailVerificationScreen = this.GetEmailVerificationScreen.bind(this);
    this.TriggerEmailVerification = this.TriggerEmailVerification.bind(this);
    this.GetPanVerificationScreen = this.GetPanVerificationScreen.bind(this);
    this.TriggerPanVerification = this.TriggerPanVerification.bind(this);
    this.GetLivenessCheckScreen = this.GetLivenessCheckScreen.bind(this);
    this.TriggerLivenessCheck = this.TriggerLivenessCheck.bind(this);
  }
  GetPhoneVerificationScreen(request: EmptyRequest): Promise<GetPhoneVerificationScreenResponse> {
    const data = EmptyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPhoneVerificationScreen", data);
    return promise.then((data) => GetPhoneVerificationScreenResponse.decode(_m0.Reader.create(data)));
  }

  TriggerPhoneVerification(request: TriggerPhoneOTPVerificationRequest): Promise<TriggerPhoneVerificationResponse> {
    const data = TriggerPhoneOTPVerificationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TriggerPhoneVerification", data);
    return promise.then((data) => TriggerPhoneVerificationResponse.decode(_m0.Reader.create(data)));
  }

  GetPhoneOTPVerificationScreen(request: EmptyRequest): Promise<GetPhoneOTPVerificationScreenResponse> {
    const data = EmptyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPhoneOTPVerificationScreen", data);
    return promise.then((data) => GetPhoneOTPVerificationScreenResponse.decode(_m0.Reader.create(data)));
  }

  TriggerPhoneOTPVerification(
    request: TriggerPhoneOTPVerificationRequest,
  ): Promise<TriggerPhoneOTPVerificationResponse> {
    const data = TriggerPhoneOTPVerificationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TriggerPhoneOTPVerification", data);
    return promise.then((data) => TriggerPhoneOTPVerificationResponse.decode(_m0.Reader.create(data)));
  }

  GetEmailVerificationScreen(request: EmptyRequest): Promise<GetEmailVerificationScreenResponse> {
    const data = EmptyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetEmailVerificationScreen", data);
    return promise.then((data) => GetEmailVerificationScreenResponse.decode(_m0.Reader.create(data)));
  }

  TriggerEmailVerification(request: TriggerEmailVerificationRequest): Promise<TriggerEmailVerificationResponse> {
    const data = TriggerEmailVerificationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TriggerEmailVerification", data);
    return promise.then((data) => TriggerEmailVerificationResponse.decode(_m0.Reader.create(data)));
  }

  GetPanVerificationScreen(request: EmptyRequest): Promise<GetPanVerificationScreenResponse> {
    const data = EmptyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPanVerificationScreen", data);
    return promise.then((data) => GetPanVerificationScreenResponse.decode(_m0.Reader.create(data)));
  }

  TriggerPanVerification(request: TriggerPanVerificationRequest): Promise<TriggerPanVerificationResponse> {
    const data = TriggerPanVerificationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TriggerPanVerification", data);
    return promise.then((data) => TriggerPanVerificationResponse.decode(_m0.Reader.create(data)));
  }

  GetLivenessCheckScreen(request: EmptyRequest): Promise<GetLivenessCheckScreenResponse> {
    const data = EmptyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetLivenessCheckScreen", data);
    return promise.then((data) => GetLivenessCheckScreenResponse.decode(_m0.Reader.create(data)));
  }

  TriggerLivenessCheck(request: TriggerLivenessCheckRequest): Promise<TriggerLivenessCheckResponse> {
    const data = TriggerLivenessCheckRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "TriggerLivenessCheck", data);
    return promise.then((data) => TriggerLivenessCheckResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
