// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "core/core-enums.proto" (package "core", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum core.Platform
 */
export enum Platform {
    /**
     * @generated from protobuf enum value: PLATFORM_NOT_DEFINED = 0;
     */
    NOT_DEFINED = 0,
    /**
     * @generated from protobuf enum value: PLATFORM_ANDROID = 1;
     */
    ANDROID = 1,
    /**
     * @generated from protobuf enum value: PLATFORM_IOS = 2;
     */
    IOS = 2,
    /**
     * @generated from protobuf enum value: PLATFORM_WEB = 3;
     */
    WEB = 3
}
/**
 * @generated from protobuf enum core.ResponseCode
 */
export enum ResponseCode {
    /**
     * General
     * frontend will only be concerned about successful or failure from the server ,
     * anything on server side does not matter for the frontend server hence we can have only 3 cases to suffice frontend responses
     *
     * @generated from protobuf enum value: RESPONSE_CODE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: RESPONSE_CODE_SUCCESS = 1;
     */
    SUCCESS = 1,
    /**
     * @generated from protobuf enum value: RESPONSE_CODE_FAILED = 2;
     */
    FAILED = 2,
    /**
     * Client Errors
     *
     * Status Code : 400
     *
     * @generated from protobuf enum value: RESPONSE_CODE_BAD_REQUEST = 3;
     */
    BAD_REQUEST = 3,
    /**
     * Status Code : 401
     *
     * @generated from protobuf enum value: RESPONSE_CODE_UNAUTHORIZED = 4;
     */
    UNAUTHORIZED = 4,
    /**
     * Status Code : 403
     *
     * @generated from protobuf enum value: RESPONSE_CODE_FORBIDDEN = 5;
     */
    FORBIDDEN = 5,
    /**
     * Status Code : 404
     *
     * @generated from protobuf enum value: RESPONSE_CODE_NOT_FOUND = 6;
     */
    NOT_FOUND = 6,
    /**
     * Status Code : 405
     *
     * @generated from protobuf enum value: RESPONSE_CODE_METHOD_NOT_ALLOWED = 7;
     */
    METHOD_NOT_ALLOWED = 7,
    /**
     * Status Code : 409
     *
     * @generated from protobuf enum value: RESPONSE_CODE_CONFLICT = 8;
     */
    CONFLICT = 8,
    /**
     * Status Code : 413
     *
     * @generated from protobuf enum value: RESPONSE_CODE_PAYLOAD_TOO_LARGE = 9;
     */
    PAYLOAD_TOO_LARGE = 9,
    /**
     * Status Code : 415
     *
     * @generated from protobuf enum value: RESPONSE_CODE_UNSUPPORTED_MEDIA_TYPE = 10;
     */
    UNSUPPORTED_MEDIA_TYPE = 10,
    /**
     * Status Code : 422
     *
     * @generated from protobuf enum value: RESPONSE_CODE_UNPROCESSABLE_ENTITY = 11;
     */
    UNPROCESSABLE_ENTITY = 11,
    /**
     * Server Errors
     *
     * Status Code : 500
     *
     * @generated from protobuf enum value: RESPONSE_CODE_INTERNAL_SERVER_ERROR = 12;
     */
    INTERNAL_SERVER_ERROR = 12,
    /**
     * Status Code : 501
     *
     * @generated from protobuf enum value: RESPONSE_CODE_NOT_IMPLEMENTED = 13;
     */
    NOT_IMPLEMENTED = 13,
    /**
     * Status Code : 502
     *
     * @generated from protobuf enum value: RESPONSE_CODE_BAD_GATEWAY = 14;
     */
    BAD_GATEWAY = 14,
    /**
     * Status Code : 503
     *
     * @generated from protobuf enum value: RESPONSE_CODE_SERVICE_UNAVAILABLE = 15;
     */
    SERVICE_UNAVAILABLE = 15,
    /**
     * Status Code : 504
     *
     * @generated from protobuf enum value: RESPONSE_CODE_GATEWAY_TIMEOUT = 16;
     */
    GATEWAY_TIMEOUT = 16,
    /**
     * Application-specific
     *
     * Status Code : 1001
     *
     * @generated from protobuf enum value: RESPONSE_CODE_VALIDATION_ERROR = 17;
     */
    VALIDATION_ERROR = 17,
    /**
     * Status Code : 1002
     *
     * @generated from protobuf enum value: RESPONSE_CODE_RESOURCE_EXHAUSTED = 18;
     */
    RESOURCE_EXHAUSTED = 18,
    /**
     * Status Code : 1003
     *
     * @generated from protobuf enum value: RESPONSE_CODE_RATE_LIMIT_EXCEEDED = 19;
     */
    RATE_LIMIT_EXCEEDED = 19,
    /**
     * Status Code : 1004
     *
     * @generated from protobuf enum value: RESPONSE_CODE_DEPRECATED_API = 20;
     */
    DEPRECATED_API = 20
}
