// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/deeplink/deeplink.proto" (package "deeplink", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { HomePodDeeplink } from "./home_deeplinks";
import { OnboardingPodDeeplink } from "./onboarding_deeplinks";
/**
 * @generated from protobuf message deeplink.Deeplink
 */
export interface Deeplink {
    /**
     * @generated from protobuf oneof: Pod
     */
    pod: {
        oneofKind: "onboardingDeeplink";
        /**
         * @generated from protobuf field: deeplink.OnboardingPodDeeplink onboarding_deeplink = 1;
         */
        onboardingDeeplink: OnboardingPodDeeplink;
    } | {
        oneofKind: "homeDeeplink";
        /**
         * @generated from protobuf field: deeplink.HomePodDeeplink home_deeplink = 2;
         */
        homeDeeplink: HomePodDeeplink;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class Deeplink$Type extends MessageType<Deeplink> {
    constructor() {
        super("deeplink.Deeplink", [
            { no: 1, name: "onboarding_deeplink", kind: "message", oneof: "pod", T: () => OnboardingPodDeeplink },
            { no: 2, name: "home_deeplink", kind: "message", oneof: "pod", T: () => HomePodDeeplink }
        ]);
    }
    create(value?: PartialMessage<Deeplink>): Deeplink {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pod = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<Deeplink>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Deeplink): Deeplink {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* deeplink.OnboardingPodDeeplink onboarding_deeplink */ 1:
                    message.pod = {
                        oneofKind: "onboardingDeeplink",
                        onboardingDeeplink: OnboardingPodDeeplink.internalBinaryRead(reader, reader.uint32(), options, (message.pod as any).onboardingDeeplink)
                    };
                    break;
                case /* deeplink.HomePodDeeplink home_deeplink */ 2:
                    message.pod = {
                        oneofKind: "homeDeeplink",
                        homeDeeplink: HomePodDeeplink.internalBinaryRead(reader, reader.uint32(), options, (message.pod as any).homeDeeplink)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Deeplink, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* deeplink.OnboardingPodDeeplink onboarding_deeplink = 1; */
        if (message.pod.oneofKind === "onboardingDeeplink")
            OnboardingPodDeeplink.internalBinaryWrite(message.pod.onboardingDeeplink, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* deeplink.HomePodDeeplink home_deeplink = 2; */
        if (message.pod.oneofKind === "homeDeeplink")
            HomePodDeeplink.internalBinaryWrite(message.pod.homeDeeplink, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message deeplink.Deeplink
 */
export const Deeplink = new Deeplink$Type();
