// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/deeplink/home_deeplinks.proto" (package "deeplink", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { DummyHomeScreen } from "../screens/home_screen_options";
/**
 * @generated from protobuf message deeplink.HomePodDeeplink
 */
export interface HomePodDeeplink {
    /**
     * @generated from protobuf oneof: Screen
     */
    screen: {
        oneofKind: "dummyScreen";
        /**
         * TODO :need to be removed once we have some screens in home
         *
         * @generated from protobuf field: screens.DummyHomeScreen dummy_screen = 1;
         */
        dummyScreen: DummyHomeScreen;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class HomePodDeeplink$Type extends MessageType<HomePodDeeplink> {
    constructor() {
        super("deeplink.HomePodDeeplink", [
            { no: 1, name: "dummy_screen", kind: "message", oneof: "screen", T: () => DummyHomeScreen }
        ]);
    }
    create(value?: PartialMessage<HomePodDeeplink>): HomePodDeeplink {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.screen = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<HomePodDeeplink>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HomePodDeeplink): HomePodDeeplink {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* screens.DummyHomeScreen dummy_screen */ 1:
                    message.screen = {
                        oneofKind: "dummyScreen",
                        dummyScreen: DummyHomeScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).dummyScreen)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HomePodDeeplink, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* screens.DummyHomeScreen dummy_screen = 1; */
        if (message.screen.oneofKind === "dummyScreen")
            DummyHomeScreen.internalBinaryWrite(message.screen.dummyScreen, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message deeplink.HomePodDeeplink
 */
export const HomePodDeeplink = new HomePodDeeplink$Type();
