// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "protos-frontend/deeplink/onboarding_deeplinks.proto" (package "deeplink", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { TermsConditionsScreen } from "../onboarding/screen_options";
import { EmailVerificationScreen } from "../onboarding/screen_options";
import { PhoneOTPScreen } from "../onboarding/screen_options";
import { PhoneVerificationScreen } from "../onboarding/screen_options";
import { PanVerificationScreen } from "../onboarding/screen_options";
import { LivenessCheckScreen } from "../onboarding/screen_options";
import { BiometricConsentScreen } from "../onboarding/screen_options";
import { OtherConsentsScreen } from "../onboarding/screen_options";
/**
 * @generated from protobuf message deeplink.OnboardingPodDeeplink
 */
export interface OnboardingPodDeeplink {
    /**
     * @generated from protobuf oneof: Screen
     */
    screen: {
        oneofKind: "otherConsentScreen";
        /**
         * @generated from protobuf field: onboarding.OtherConsentsScreen other_consent_screen = 1;
         */
        otherConsentScreen: OtherConsentsScreen;
    } | {
        oneofKind: "biometricConsentScreen";
        /**
         * @generated from protobuf field: onboarding.BiometricConsentScreen biometric_consent_screen = 2;
         */
        biometricConsentScreen: BiometricConsentScreen;
    } | {
        oneofKind: "livenessCheckScreen";
        /**
         * @generated from protobuf field: onboarding.LivenessCheckScreen liveness_check_screen = 3;
         */
        livenessCheckScreen: LivenessCheckScreen;
    } | {
        oneofKind: "panVerificationScreen";
        /**
         * @generated from protobuf field: onboarding.PanVerificationScreen pan_verification_screen = 4;
         */
        panVerificationScreen: PanVerificationScreen;
    } | {
        oneofKind: "phoneVerificationScreen";
        /**
         * @generated from protobuf field: onboarding.PhoneVerificationScreen phone_verification_screen = 5;
         */
        phoneVerificationScreen: PhoneVerificationScreen;
    } | {
        oneofKind: "phoneOtpScreen";
        /**
         * @generated from protobuf field: onboarding.PhoneOTPScreen phone_otp_screen = 6;
         */
        phoneOtpScreen: PhoneOTPScreen;
    } | {
        oneofKind: "emailVerificationScreen";
        /**
         * @generated from protobuf field: onboarding.EmailVerificationScreen email_verification_screen = 7;
         */
        emailVerificationScreen: EmailVerificationScreen;
    } | {
        oneofKind: "termsConditionsScreen";
        /**
         * @generated from protobuf field: onboarding.TermsConditionsScreen terms_conditions_screen = 8;
         */
        termsConditionsScreen: TermsConditionsScreen;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class OnboardingPodDeeplink$Type extends MessageType<OnboardingPodDeeplink> {
    constructor() {
        super("deeplink.OnboardingPodDeeplink", [
            { no: 1, name: "other_consent_screen", kind: "message", oneof: "screen", T: () => OtherConsentsScreen },
            { no: 2, name: "biometric_consent_screen", kind: "message", oneof: "screen", T: () => BiometricConsentScreen },
            { no: 3, name: "liveness_check_screen", kind: "message", oneof: "screen", T: () => LivenessCheckScreen },
            { no: 4, name: "pan_verification_screen", kind: "message", oneof: "screen", T: () => PanVerificationScreen },
            { no: 5, name: "phone_verification_screen", kind: "message", oneof: "screen", T: () => PhoneVerificationScreen },
            { no: 6, name: "phone_otp_screen", kind: "message", oneof: "screen", T: () => PhoneOTPScreen },
            { no: 7, name: "email_verification_screen", kind: "message", oneof: "screen", T: () => EmailVerificationScreen },
            { no: 8, name: "terms_conditions_screen", kind: "message", oneof: "screen", T: () => TermsConditionsScreen }
        ]);
    }
    create(value?: PartialMessage<OnboardingPodDeeplink>): OnboardingPodDeeplink {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.screen = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<OnboardingPodDeeplink>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OnboardingPodDeeplink): OnboardingPodDeeplink {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* onboarding.OtherConsentsScreen other_consent_screen */ 1:
                    message.screen = {
                        oneofKind: "otherConsentScreen",
                        otherConsentScreen: OtherConsentsScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).otherConsentScreen)
                    };
                    break;
                case /* onboarding.BiometricConsentScreen biometric_consent_screen */ 2:
                    message.screen = {
                        oneofKind: "biometricConsentScreen",
                        biometricConsentScreen: BiometricConsentScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).biometricConsentScreen)
                    };
                    break;
                case /* onboarding.LivenessCheckScreen liveness_check_screen */ 3:
                    message.screen = {
                        oneofKind: "livenessCheckScreen",
                        livenessCheckScreen: LivenessCheckScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).livenessCheckScreen)
                    };
                    break;
                case /* onboarding.PanVerificationScreen pan_verification_screen */ 4:
                    message.screen = {
                        oneofKind: "panVerificationScreen",
                        panVerificationScreen: PanVerificationScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).panVerificationScreen)
                    };
                    break;
                case /* onboarding.PhoneVerificationScreen phone_verification_screen */ 5:
                    message.screen = {
                        oneofKind: "phoneVerificationScreen",
                        phoneVerificationScreen: PhoneVerificationScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).phoneVerificationScreen)
                    };
                    break;
                case /* onboarding.PhoneOTPScreen phone_otp_screen */ 6:
                    message.screen = {
                        oneofKind: "phoneOtpScreen",
                        phoneOtpScreen: PhoneOTPScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).phoneOtpScreen)
                    };
                    break;
                case /* onboarding.EmailVerificationScreen email_verification_screen */ 7:
                    message.screen = {
                        oneofKind: "emailVerificationScreen",
                        emailVerificationScreen: EmailVerificationScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).emailVerificationScreen)
                    };
                    break;
                case /* onboarding.TermsConditionsScreen terms_conditions_screen */ 8:
                    message.screen = {
                        oneofKind: "termsConditionsScreen",
                        termsConditionsScreen: TermsConditionsScreen.internalBinaryRead(reader, reader.uint32(), options, (message.screen as any).termsConditionsScreen)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OnboardingPodDeeplink, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* onboarding.OtherConsentsScreen other_consent_screen = 1; */
        if (message.screen.oneofKind === "otherConsentScreen")
            OtherConsentsScreen.internalBinaryWrite(message.screen.otherConsentScreen, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.BiometricConsentScreen biometric_consent_screen = 2; */
        if (message.screen.oneofKind === "biometricConsentScreen")
            BiometricConsentScreen.internalBinaryWrite(message.screen.biometricConsentScreen, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.LivenessCheckScreen liveness_check_screen = 3; */
        if (message.screen.oneofKind === "livenessCheckScreen")
            LivenessCheckScreen.internalBinaryWrite(message.screen.livenessCheckScreen, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.PanVerificationScreen pan_verification_screen = 4; */
        if (message.screen.oneofKind === "panVerificationScreen")
            PanVerificationScreen.internalBinaryWrite(message.screen.panVerificationScreen, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.PhoneVerificationScreen phone_verification_screen = 5; */
        if (message.screen.oneofKind === "phoneVerificationScreen")
            PhoneVerificationScreen.internalBinaryWrite(message.screen.phoneVerificationScreen, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.PhoneOTPScreen phone_otp_screen = 6; */
        if (message.screen.oneofKind === "phoneOtpScreen")
            PhoneOTPScreen.internalBinaryWrite(message.screen.phoneOtpScreen, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.EmailVerificationScreen email_verification_screen = 7; */
        if (message.screen.oneofKind === "emailVerificationScreen")
            EmailVerificationScreen.internalBinaryWrite(message.screen.emailVerificationScreen, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* onboarding.TermsConditionsScreen terms_conditions_screen = 8; */
        if (message.screen.oneofKind === "termsConditionsScreen")
            TermsConditionsScreen.internalBinaryWrite(message.screen.termsConditionsScreen, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message deeplink.OnboardingPodDeeplink
 */
export const OnboardingPodDeeplink = new OnboardingPodDeeplink$Type();
